# **AutoInsight AI — Análise Exploratória**

## 1. Profiling inicial dos dados

In [2]:
import pandas as pd
import numpy as np
# import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Ambiente configurado!")

Ambiente configurado!

In [3]:
import pandas as pd
from pathlib import Path

DATA_PATH = Path(r"C:\Users\Clebe\Downloads\AutoInsight AI\fipex-prices-latest-merged.parquet")

df = pd.read_parquet(DATA_PATH)

print(f"Linhas: {df.shape[0]:,}")
print(f"Colunas: {df.shape[1]}")

display(df.head())

Linhas: 9,580,464
Colunas: 12

,tipo_veiculo,codigo_fipe,nome_modelo,nome_marca,nome_combustivel,sigla_combustivel,ano_modelo,zero_km,valor_centavos,valor_formatado,mes_referencia,ano_referencia
0,moto,840015-6,ATV 100,ADLY,Gasolina,g,1990.0,False,0,"R$ 0,00",9,2012
1,moto,840015-6,ATV 100,ADLY,Gasolina,g,1991.0,False,0,"R$ 0,00",9,2012
2,moto,840015-6,ATV 100,ADLY,Gasolina,g,1992.0,False,0,"R$ 0,00",9,2012
3,moto,840015-6,ATV 100,ADLY,Gasolina,g,1993.0,False,0,"R$ 0,00",9,2012
4,moto,840015-6,ATV 100,ADLY,Gasolina,g,1994.0,False,0,"R$ 0,00",9,2012

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9580464 entries, 0 to 9580463
Data columns (total 12 columns):
 #   Column             Dtype
---  ------             -----
 0   tipo_veiculo       object
 1   codigo_fipe        object
 2   nome_modelo        object
 3   nome_marca         object
 4   nome_combustivel   object
 5   sigla_combustivel  object
 6   ano_modelo         float64
 7   zero_km            bool
 8   valor_centavos     int64
 9   valor_formatado    object
 10  mes_referencia     int32
 11  ano_referencia     int32
dtypes: bool(1), float64(1), int32(2), int64(1), object(7)
memory usage: 740.1+ MB

In [5]:
df.columns.tolist()

['tipo_veiculo',
 'codigo_fipe',
 'nome_modelo',
 'nome_marca',
 'nome_combustivel',
 'sigla_combustivel',
 'ano_modelo',
 'zero_km',
 'valor_centavos',
 'valor_formatado',
 'mes_referencia',
 'ano_referencia']

In [6]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
tipo_veiculo,9580464,3,carro,5892768,NaN,NaN,NaN,NaN,NaN,NaN,NaN
codigo_fipe,9580464,11424,005024-5,10376,NaN,NaN,NaN,NaN,NaN,NaN,NaN
nome_modelo,9580464,11432,Kombi Standard/ Luxo/ Série Prata,10376,NaN,NaN,NaN,NaN,NaN,NaN,NaN
nome_marca,9580464,235,VW - VolksWagen,608939,NaN,NaN,NaN,NaN,NaN,NaN,NaN
nome_combustivel,9580464,7,Gasolina,5255539,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sigla_combustivel,9580464,7,g,5255539,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ano_modelo,9070581.0,NaN,NaN,NaN,2004.052645,9.502905,1981.0,1997.0,2004.0,2011.0,2027.0
zero_km,9580464,2,False,9070581,NaN,NaN,NaN,NaN,NaN,NaN,NaN
valor_centavos,9580464.0,NaN,NaN,NaN,9240630.815157,21955107.546421,0.0,1764200.0,3856100.0,8955200.0,976574400.0
valor_formatado,9580464,622502,"R$ 62.627,00",646,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mes_referencia,9580464.0,NaN,NaN,NaN,6.496846,3.433324,1.0,4.0,7.0,9.0,12.0
ano_referencia,9580464.0,NaN,NaN,NaN,2016.183035,6.950112,2001.0,2011.0,2017.0,2022.0,2026.0

In [7]:
df.isnull().sum().sort_values(ascending=False)

ano_modelo           509883
tipo_veiculo              0
nome_modelo               0
codigo_fipe               0
nome_marca                0
nome_combustivel          0
sigla_combustivel         0
zero_km                   0
valor_centavos            0
valor_formatado           0
mes_referencia            0
ano_referencia            0
dtype: int64

In [8]:
print("Duplicados:", df.duplicated().sum())

Duplicados: 83

In [9]:
df.dtypes

tipo_veiculo          object
codigo_fipe           object
nome_modelo           object
nome_marca            object
nome_combustivel      object
sigla_combustivel     object
ano_modelo           float64
zero_km                 bool
valor_centavos         int64
valor_formatado       object
mes_referencia         int32
ano_referencia         int32
dtype: object

In [10]:
nulos = (
    df.isnull()
      .sum()
      .to_frame("quantidade")
)

nulos["percentual"] = (
    nulos["quantidade"] / len(df) * 100
).round(2)

nulos.sort_values("percentual", ascending=False)

                   quantidade  percentual
ano_modelo             509883        5.32
tipo_veiculo                0        0.00
nome_modelo                 0        0.00
codigo_fipe                 0        0.00
nome_marca                  0        0.00
nome_combustivel            0        0.00
sigla_combustivel           0        0.00
zero_km                     0        0.00
valor_centavos              0        0.00
valor_formatado             0        0.00
mes_referencia              0        0.00
ano_referencia              0        0.00

In [11]:
duplicados = df.duplicated().sum()

print(f"Registros duplicados: {duplicados:,}")
print(f"Percentual: {duplicados / len(df) * 100:.2f}%")

Registros duplicados: 83
Percentual: 0.00%

In [12]:
print("Ano mínimo:", df["ano_referencia"].min())
print("Ano máximo:", df["ano_referencia"].max())

print(
    "Meses de referência:",
    sorted(df["mes_referencia"].dropna().unique())
)

Ano mínimo: 2001
Ano máximo: 2026
Meses de referência: [np.int32(1), np.int32(2), np.int32(3), np.int32(4), np.int32(5), np.int32(6), np.int32(7), np.int32(8), np.int32(9), np.int32(10), np.int32(11), np.int32(12)]

In [13]:
print("Tipos de veículo:")
print(df["tipo_veiculo"].value_counts())

print("\nQuantidade de marcas:")
print(df["nome_marca"].nunique())

print("\nQuantidade de modelos:")
print(df["nome_modelo"].nunique())

print("\nCódigos FIPE:")
print(df["codigo_fipe"].nunique())

Tipos de veículo:
tipo_veiculo
carro       5892768
caminhão    2178151
moto        1509545
Name: count, dtype: int64

Quantidade de marcas:
235

Quantidade de modelos:
11432

Códigos FIPE:
11424

In [14]:
preco_zero = (df["valor_centavos"] == 0).sum()

print(f"Preços zerados: {preco_zero:,}")
print(f"Percentual: {preco_zero / len(df) * 100:.2f}%")

Preços zerados: 22
Percentual: 0.00%

In [15]:
df["tipo_veiculo"].value_counts(dropna=False)

tipo_veiculo
carro       5892768
caminhão    2178151
moto        1509545
Name: count, dtype: int64

In [16]:
df["preco"] = df["valor_centavos"] / 100

In [17]:
diagnostico = pd.DataFrame({
    "tipo": df.dtypes.astype(str),
    "nulos": df.isnull().sum(),
    "nulos_%": (df.isnull().mean() * 100).round(2),
    "unicos": df.nunique()
})

diagnostico

                      tipo   nulos  nulos_%  unicos
tipo_veiculo        object       0     0.00       3
codigo_fipe         object       0     0.00   11424
nome_modelo         object       0     0.00   11432
nome_marca          object       0     0.00     235
nome_combustivel    object       0     0.00       7
sigla_combustivel   object       0     0.00       7
ano_modelo         float64  509883     5.32      47
zero_km               bool       0     0.00       2
valor_centavos       int64       0     0.00  622502
valor_formatado     object       0     0.00  622502
mes_referencia       int32       0     0.00      12
ano_referencia       int32       0     0.00      26
preco              float64       0     0.00  622502

In [18]:
df[df["ano_modelo"].isna()][
    [
        "tipo_veiculo",
        "codigo_fipe",
        "nome_marca",
        "nome_modelo",
        "nome_combustivel",
        "ano_modelo",
        "zero_km",
        "preco",
        "mes_referencia",
        "ano_referencia"
    ]
].head(20)

,tipo_veiculo,codigo_fipe,nome_marca,nome_modelo,nome_combustivel,ano_modelo,zero_km,preco,mes_referencia,ano_referencia
925,moto,840015-6,ADLY,ATV 100,Gasolina,NaN,True,0.0,9,2012
926,moto,840015-6,ADLY,ATV 100,Gasolina,NaN,True,10258.0,12,2004
927,moto,840015-6,ADLY,ATV 100,Gasolina,NaN,True,10271.0,11,2004
928,moto,840015-6,ADLY,ATV 100,Gasolina,NaN,True,10271.0,10,2004
929,moto,840015-6,ADLY,ATV 100,Gasolina,NaN,True,10124.0,9,2004
930,moto,840015-6,ADLY,ATV 100,Gasolina,NaN,True,10116.0,8,2004
931,moto,840015-6,ADLY,ATV 100,Gasolina,NaN,True,10086.0,7,2004
932,moto,840015-6,ADLY,ATV 100,Gasolina,NaN,True,10124.0,6,2004
933,moto,840015-6,ADLY,ATV 100,Gasolina,NaN,True,10520.0,5,2004
934,moto,840015-6,ADLY,ATV 100,Gasolina,NaN,True,10071.0,4,2004
935,moto,840015-6,ADLY,ATV 100,Gasolina,NaN,True,10124.0,3,2004
936,moto,840015-6,ADLY,ATV 100,Gasolina,NaN,True,10159.0,2,2004
937,moto,840015-6,ADLY,ATV 100,Gasolina,NaN,True,10243.0,1,2004
938,moto,840015-6,ADLY,ATV 100,Gasolina,NaN,True,10366.0,12,2003
939,moto,840015-6,ADLY,ATV 100,Gasolina,NaN,True,10314.0,11,2003
940,moto,840015-6,ADLY,ATV 100,Gasolina,NaN,True,10292.0,10,2003
941,moto,840015-6,ADLY,ATV 100,Gasolina,NaN,True,10370.0,9,2003
942,moto,840015-6,ADLY,ATV 100,Gasolina,NaN,True,10287.0,8,2003
943,moto,840015-6,ADLY,ATV 100,Gasolina,NaN,True,10547.0,7,2003
944,moto,840015-6,ADLY,ATV 100,Gasolina,NaN,True,10829.0,6,2003

In [19]:
pd.crosstab(
    df["ano_modelo"].isna(),
    df["zero_km"],
    margins=True
)

zero_km       False    True      All
ano_modelo
False       9070581       0  9070581
True              0  509883   509883
All         9070581  509883  9580464

In [20]:
df.groupby("zero_km").agg(
    quantidade=("codigo_fipe", "size"),
    preco_medio=("preco", "mean"),
    preco_mediano=("preco", "median")
).round(2)

         quantidade  preco_medio  preco_mediano
zero_km
False       9070581     85164.63        36745.0
True         509883    221232.35        98258.0

In [21]:
qtd_zero = (df["preco"] == 0).sum()

print(f"Preços zerados: {qtd_zero:,}")
print(f"Percentual: {qtd_zero / len(df) * 100:.2f}%")

Preços zerados: 22
Percentual: 0.00%

In [22]:
df[df["preco"] == 0][
    [
        "tipo_veiculo",
        "nome_marca",
        "nome_modelo",
        "ano_modelo",
        "zero_km",
        "mes_referencia",
        "ano_referencia"
    ]
].head(20)

,tipo_veiculo,nome_marca,nome_modelo,ano_modelo,zero_km,mes_referencia,ano_referencia
0,moto,ADLY,ATV 100,1990.0,False,9,2012
1,moto,ADLY,ATV 100,1991.0,False,9,2012
2,moto,ADLY,ATV 100,1992.0,False,9,2012
3,moto,ADLY,ATV 100,1993.0,False,9,2012
4,moto,ADLY,ATV 100,1994.0,False,9,2012
5,moto,ADLY,ATV 100,1995.0,False,9,2012
6,moto,ADLY,ATV 100,1996.0,False,9,2012
7,moto,ADLY,ATV 100,1997.0,False,9,2012
8,moto,ADLY,ATV 100,1998.0,False,9,2012
9,moto,ADLY,ATV 100,1999.0,False,9,2012
914,moto,ADLY,ATV 100,2003.0,False,9,2012
915,moto,ADLY,ATV 100,2004.0,False,9,2012
916,moto,ADLY,ATV 100,2005.0,False,9,2012
917,moto,ADLY,ATV 100,2006.0,False,9,2012
918,moto,ADLY,ATV 100,2007.0,False,9,2012
919,moto,ADLY,ATV 100,2008.0,False,9,2012
920,moto,ADLY,ATV 100,2009.0,False,9,2012
921,moto,ADLY,ATV 100,2010.0,False,9,2012
922,moto,ADLY,ATV 100,2011.0,False,9,2012
923,moto,ADLY,ATV 100,2012.0,False,9,2012

In [23]:
df["tipo_veiculo"].value_counts()

tipo_veiculo
carro       5892768
caminhão    2178151
moto        1509545
Name: count, dtype: int64

In [24]:
print("=== ANO_MODELO NULO x ZERO_KM ===")

display(
    pd.crosstab(
        df["ano_modelo"].isna(),
        df["zero_km"],
        margins=True
    )
)

print("\n=== PREÇOS ZERADOS ===")

qtd_zero = (df["preco"] == 0).sum()

print(f"Quantidade: {qtd_zero:,}")
print(f"Percentual: {qtd_zero / len(df) * 100:.2f}%")

=== ANO_MODELO NULO x ZERO_KM ===

zero_km       False    True      All
ano_modelo
False       9070581       0  9070581
True              0  509883   509883
All         9070581  509883  9580464

=== PREÇOS ZERADOS ===
Quantidade: 22
Percentual: 0.00%

In [25]:
df_carros = df[
    df["tipo_veiculo"] == "carro"
].copy()

print(f"Base original: {len(df):,}")
print(f"Base de carros: {len(df_carros):,}")

Base original: 9,580,464
Base de carros: 5,892,768

In [26]:
df_carros["preco"] = (
    df_carros["valor_centavos"] / 100
)

In [27]:
qtd_antes = len(df_carros)

df_carros = df_carros[
    df_carros["preco"] > 0
].copy()

qtd_depois = len(df_carros)

print(f"Antes: {qtd_antes:,}")
print(f"Depois: {qtd_depois:,}")
print(f"Removidos: {qtd_antes - qtd_depois:,}")

Antes: 5,892,768
Depois: 5,892,768
Removidos: 0

In [28]:
df_carros["data_referencia"] = pd.to_datetime(
    dict(
        year=df_carros["ano_referencia"],
        month=df_carros["mes_referencia"],
        day=1
    )
)

In [29]:
df_carros[
    [
        "mes_referencia",
        "ano_referencia",
        "data_referencia"
    ]
].head()

       mes_referencia  ano_referencia data_referencia
89541              10            2026      2026-10-01
89542               9            2026      2026-09-01
89543               8            2026      2026-08-01
89544               7            2026      2026-07-01
89545               6            2026      2026-06-01

In [30]:
print(
    "Início:",
    df_carros["data_referencia"].min()
)

print(
    "Fim:",
    df_carros["data_referencia"].max()
)

Início: 2001-01-01 00:00:00
Fim: 2026-10-01 00:00:00

In [31]:
df_carros["ano_modelo"].fillna(0)

89541      1998.0
89542      1998.0
89543      1998.0
89544      1998.0
89545      1998.0
            ...
9580459       0.0
9580460       0.0
9580461       0.0
9580462       0.0
9580463       0.0
Name: ano_modelo, Length: 5892768, dtype: float64

In [32]:
df_carros[
    df_carros["nome_modelo"]
        .str.contains("ARGO", case=False, na=False)
][
    [
        "codigo_fipe",
        "nome_marca",
        "nome_modelo"
    ]
].drop_duplicates().head(30)

        codigo_fipe nome_marca                              nome_modelo
113390     309001-9      ARROW                     2 Urban Cargo 85 5m³
113392     309002-7      ARROW                     2 Urban Cargo 85 7m³
834146     064002-6      CHANA              Cargo 1.0 8V 53cv (Pick-Up)
835906     064004-2      CHANA           Cargo CD 1.0 8V 53cv (Pick-Up)
837217     064003-4      CHANA           Cargo CE 1.0 8V 53cv (Pick-Up)
1043518    011214-3    Citroën    Jumper 2.0 Cargo Furgão 16V TB Diesel
1053988    011220-8    Citroën            Jumper Cargo 2.2 Turbo Diesel
1055843    011244-5    Citroën                   Jumpy 2.2  Cargo Turbo
1055916    011216-0    Citroën             Jumpy Cargo 1.5 Turbo Diesel
1121636    011218-6    Citroën           Ë-Jumpy Cargo 136cv (Elétrico)
1660296    001509-1       Fiat                         ARGO 1.0 6V Flex
1660956    001494-0       Fiat                   ARGO DRIVE 1.0 6V Flex
1661639    001493-1       Fiat                   ARGO DRIVE 1.3 8V Flex
1662067    001561-0       Fiat              ARGO DRIVE 1.3 8V Flex Aut.
1662240    001492-3       Fiat               ARGO DRIVE GSR 1.3 8V Flex
1662583    001540-7       Fiat          ARGO DRIVE S-DESIGN 1.3 8V Flex
1662719    001583-0       Fiat       ARGO DRIVE TRIBUTO 125 1.0 6V Flex
1662752    001576-8       Fiat               ARGO ENDURANCE 1.3 8V Flex
1662786    001488-5       Fiat               ARGO HGT 1.8 16V Flex Aut.
1663217    001490-7       Fiat               ARGO HGT 1.8 16V Flex Mec.
1663455    001489-3       Fiat         ARGO PRECISION 1.8 16V Flex Aut.
1663803    001491-5       Fiat         ARGO PRECISION 1.8 16V Flex Mec.
1664038    001519-9       Fiat                ARGO TREKKING 1.3 8V Flex
1664483    001562-8       Fiat           ARGO TREKKING 1.3 8V Flex Aut.
1664656    001524-5       Fiat          ARGO TREKKING 1.8 16V Flex Aut.
1680792    001302-1       Fiat     Doblo  Cargo 1.4 mpi Fire Flex 8V 3p
1687318    001170-3       Fiat            Doblo Cargo 1.3 Fire 16V 4/5p
1688769    001169-0       Fiat                 Doblo Cargo 1.6 16V 4/5p
1689387    001206-8       Fiat             Doblo Cargo 1.8 mpi 8V 103cv
1690232    001235-1       Fiat  Doblo Cargo 1.8 mpi Fire Flex 8V/16V 4p

In [33]:
argo = df_carros[
    df_carros["codigo_fipe"] == "001494-0"
].copy()

print(f"Registros encontrados: {len(argo):,}")

display(
    argo[
        [
            "codigo_fipe",
            "nome_marca",
            "nome_modelo",
            "ano_modelo",
            "zero_km",
            "preco",
            "data_referencia"
        ]
    ].head(20)
)

Registros encontrados: 683

,codigo_fipe,nome_marca,nome_modelo,ano_modelo,zero_km,preco,data_referencia
1660956,001494-0,Fiat,ARGO DRIVE 1.0 6V Flex,2018.0,False,48378.0,2026-10-01
1660957,001494-0,Fiat,ARGO DRIVE 1.0 6V Flex,2018.0,False,48622.0,2026-09-01
1660958,001494-0,Fiat,ARGO DRIVE 1.0 6V Flex,2018.0,False,48613.0,2026-08-01
1660959,001494-0,Fiat,ARGO DRIVE 1.0 6V Flex,2018.0,False,49340.0,2026-07-01
1660960,001494-0,Fiat,ARGO DRIVE 1.0 6V Flex,2018.0,False,49022.0,2026-06-01
1660961,001494-0,Fiat,ARGO DRIVE 1.0 6V Flex,2018.0,False,48826.0,2026-05-01
1660962,001494-0,Fiat,ARGO DRIVE 1.0 6V Flex,2018.0,False,49047.0,2026-04-01
1660963,001494-0,Fiat,ARGO DRIVE 1.0 6V Flex,2018.0,False,48110.0,2026-03-01
1660964,001494-0,Fiat,ARGO DRIVE 1.0 6V Flex,2018.0,False,48352.0,2026-02-01
1660965,001494-0,Fiat,ARGO DRIVE 1.0 6V Flex,2018.0,False,48595.0,2026-01-01
1660966,001494-0,Fiat,ARGO DRIVE 1.0 6V Flex,2018.0,False,49380.0,2025-12-01
1660967,001494-0,Fiat,ARGO DRIVE 1.0 6V Flex,2018.0,False,49629.0,2025-11-01
1660968,001494-0,Fiat,ARGO DRIVE 1.0 6V Flex,2018.0,False,49879.0,2025-10-01
1660969,001494-0,Fiat,ARGO DRIVE 1.0 6V Flex,2018.0,False,50130.0,2025-09-01
1660970,001494-0,Fiat,ARGO DRIVE 1.0 6V Flex,2018.0,False,50382.0,2025-08-01
1660971,001494-0,Fiat,ARGO DRIVE 1.0 6V Flex,2018.0,False,50636.0,2025-07-01
1660972,001494-0,Fiat,ARGO DRIVE 1.0 6V Flex,2018.0,False,50329.0,2025-06-01
1660973,001494-0,Fiat,ARGO DRIVE 1.0 6V Flex,2018.0,False,49831.0,2025-05-01
1660974,001494-0,Fiat,ARGO DRIVE 1.0 6V Flex,2018.0,False,50060.0,2025-04-01
1660975,001494-0,Fiat,ARGO DRIVE 1.0 6V Flex,2018.0,False,49754.0,2025-03-01

In [34]:
argo["ano_modelo"].value_counts(
    dropna=False
).sort_index()

ano_modelo
2018.0    112
2019.0     98
2020.0     89
2021.0     73
2022.0     64
2023.0     50
2024.0     38
2025.0     29
2026.0     18
NaN       112
Name: count, dtype: int64

In [35]:
argo_2024 = (
    argo[
        (argo["ano_modelo"] == 2024) &
        (argo["zero_km"] == False)
    ]
    .sort_values("data_referencia")
    .copy()
)

print(f"Observações: {len(argo_2024)}")

print(
    "Período:",
    argo_2024["data_referencia"].min(),
    "até",
    argo_2024["data_referencia"].max()
)

display(
    argo_2024[
        ["data_referencia", "preco"]
    ].tail(10)
)

Observações: 38
Período: 2023-09-01 00:00:00 até 2026-10-01 00:00:00

        data_referencia    preco
1661451      2026-01-01  69420.0
1661450      2026-02-01  69215.0
1661449      2026-03-01  68804.0
1661448      2026-04-01  68600.0
1661447      2026-05-01  68498.0
1661446      2026-06-01  69044.0
1661445      2026-07-01  68492.0
1661444      2026-08-01  68652.0
1661443      2026-09-01  67794.0
1661442      2026-10-01  67386.0

In [36]:
argo_2024["variacao_mensal_pct"] = (
    argo_2024["preco"]
    .pct_change() * 100
)

argo_2024["variacao_12m_pct"] = (
    argo_2024["preco"]
    .pct_change(periods=12) * 100
)

In [37]:
display(
    argo_2024[
        [
            "data_referencia",
            "preco",
            "variacao_mensal_pct",
            "variacao_12m_pct"
        ]
    ].tail(15)
)

        data_referencia    preco  variacao_mensal_pct  variacao_12m_pct
1661456      2025-08-01  70323.0            -1.003716         -6.577304
1661455      2025-09-01  70113.0            -0.298622         -6.387439
1661454      2025-10-01  69902.0            -0.300943         -5.944564
1661453      2025-11-01  69989.0             0.124460         -5.292287
1661452      2025-12-01  69249.0            -1.057309         -5.211071
1661451      2026-01-01  69420.0             0.246935         -4.163676
1661450      2026-02-01  69215.0            -0.295304         -4.102472
1661449      2026-03-01  68804.0            -0.593802         -3.434338
1661448      2026-04-01  68600.0            -0.296494         -2.295904
1661447      2026-05-01  68498.0            -0.148688         -2.894811
1661446      2026-06-01  69044.0             0.797104         -3.011744
1661445      2026-07-01  68492.0            -0.799490         -3.581283
1661444      2026-08-01  68652.0             0.233604         -2.376178
1661443      2026-09-01  67794.0            -1.249782         -3.307518
1661442      2026-10-01  67386.0            -0.601823         -3.599325

In [38]:
maior_alta = argo_2024.loc[
    argo_2024["variacao_mensal_pct"].idxmax()
]

maior_queda = argo_2024.loc[
    argo_2024["variacao_mensal_pct"].idxmin()
]

print("MAIOR ALTA MENSAL")
print(f'Data: {maior_alta["data_referencia"]:%m/%Y}')
print(f'Variação: {maior_alta["variacao_mensal_pct"]:.2f}%')

print("\nMAIOR QUEDA MENSAL")
print(f'Data: {maior_queda["data_referencia"]:%m/%Y}')
print(f'Variação: {maior_queda["variacao_mensal_pct"]:.2f}%')

MAIOR ALTA MENSAL
Data: 12/2023
Variação: 3.50%

MAIOR QUEDA MENSAL
Data: 11/2023
Variação: -3.50%

In [39]:
df_modelo = df_carros[
    (df_carros["zero_km"] == False) &
    (df_carros["ano_modelo"].notna())
].copy()

df_modelo = df_modelo.sort_values(
    [
        "codigo_fipe",
        "ano_modelo",
        "data_referencia"
    ]
)

print(f"Registros para análise: {len(df_modelo):,}")

Registros para análise: 5,581,552

In [40]:
grupo = df_modelo.groupby(
    ["codigo_fipe", "ano_modelo"]
)

df_modelo["preco_mes_anterior"] = (
    grupo["preco"].shift(1)
)

In [41]:
df_modelo["variacao_mensal_pct"] = (
    (
        df_modelo["preco"]
        / df_modelo["preco_mes_anterior"]
    ) - 1
) * 100

In [42]:
df_modelo["preco_12m_atras"] = (
    grupo["preco"].shift(12)
)

df_modelo["variacao_12m_pct"] = (
    (
        df_modelo["preco"]
        / df_modelo["preco_12m_atras"]
    ) - 1
) * 100

In [43]:
df_modelo["idade_veiculo"] = (
    df_modelo["ano_referencia"]
    - df_modelo["ano_modelo"]
)

In [44]:
df_modelo[
    [
        "nome_marca",
        "nome_modelo",
        "ano_modelo",
        "data_referencia",
        "idade_veiculo",
        "preco",
        "preco_mes_anterior",
        "variacao_mensal_pct",
        "preco_12m_atras",
        "variacao_12m_pct"
    ]
].tail(20)

,nome_marca,nome_modelo,ano_modelo,data_referencia,idade_veiculo,preco,preco_mes_anterior,variacao_mensal_pct,preco_12m_atras,variacao_12m_pct
896842,Caoa Changan,AVATR11,2026.0,2026-06-01,0.0,542897.0,NaN,NaN,NaN,NaN
896841,Caoa Changan,AVATR11,2026.0,2026-07-01,0.0,542897.0,542897.0,0.000000,NaN,NaN
896840,Caoa Changan,AVATR11,2026.0,2026-08-01,0.0,541268.0,542897.0,-0.300057,NaN,NaN
896839,Caoa Changan,AVATR11,2026.0,2026-09-01,0.0,540347.0,541268.0,-0.170156,NaN,NaN
896838,Caoa Changan,AVATR11,2026.0,2026-10-01,0.0,534349.0,540347.0,-1.110027,NaN,NaN
896847,Caoa Changan,AVATR11,2027.0,2026-06-01,-1.0,568541.0,NaN,NaN,NaN,NaN
896846,Caoa Changan,AVATR11,2027.0,2026-07-01,-1.0,568541.0,568541.0,0.000000,NaN,NaN
896845,Caoa Changan,AVATR11,2027.0,2026-08-01,-1.0,566835.0,568541.0,-0.300066,NaN,NaN
896844,Caoa Changan,AVATR11,2027.0,2026-09-01,-1.0,565871.0,566835.0,-0.170067,NaN,NaN
896843,Caoa Changan,AVATR11,2027.0,2026-10-01,-1.0,559589.0,565871.0,-1.110147,NaN,NaN
896862,Caoa Changan,CS75 1.5 16V TGDi,2027.0,2026-07-01,-1.0,188933.0,NaN,NaN,NaN,NaN
896861,Caoa Changan,CS75 1.5 16V TGDi,2027.0,2026-08-01,-1.0,188933.0,188933.0,0.000000,NaN,NaN
896860,Caoa Changan,CS75 1.5 16V TGDi,2027.0,2026-09-01,-1.0,177414.0,188933.0,-6.096870,NaN,NaN
896859,Caoa Changan,CS75 1.5 16V TGDi,2027.0,2026-10-01,-1.0,175017.0,177414.0,-1.351077,NaN,NaN
896855,Caoa Changan,CS55 PRIME 1.5 16V TGDi,2027.0,2026-10-01,-1.0,137233.0,NaN,NaN,NaN,NaN
896853,Caoa Changan,CS55 INFINITY 1.5 16V TGDi,2027.0,2026-10-01,-1.0,146166.0,NaN,NaN,NaN,NaN
896857,Caoa Changan,CS55 ULTRA 1.5 16V TGDi,2027.0,2026-10-01,-1.0,178201.0,NaN,NaN,NaN,NaN
113390,ARROW,2 Urban Cargo 85 5m³,2026.0,2026-10-01,0.0,203328.0,NaN,NaN,NaN,NaN
113392,ARROW,2 Urban Cargo 85 7m³,2026.0,2026-10-01,0.0,209227.0,NaN,NaN,NaN,NaN
113394,ARROW,2 Urban Chassi 85,2026.0,2026-10-01,0.0,190366.0,NaN,NaN,NaN,NaN

In [45]:
df_modelo["idade_veiculo_raw"] = (
    df_modelo["ano_referencia"]
    - df_modelo["ano_modelo"]
)

df_modelo["idade_veiculo"] = (
    df_modelo["idade_veiculo_raw"]
    .clip(lower=0)
)

In [46]:
df_modelo["modelo_ano_futuro"] = (
    df_modelo["ano_modelo"] > df_modelo["ano_referencia"]
).astype("int8")

In [47]:
teste_argo = df_modelo[
    (df_modelo["codigo_fipe"] == "001494-0") &
    (df_modelo["ano_modelo"] == 2024)
][
    [
        "data_referencia",
        "preco",
        "preco_mes_anterior",
        "variacao_mensal_pct",
        "preco_12m_atras",
        "variacao_12m_pct"
    ]
].sort_values("data_referencia")

display(teste_argo)

,data_referencia,preco,preco_mes_anterior,variacao_mensal_pct,preco_12m_atras,variacao_12m_pct
1661479,2023-09-01,79104.0,NaN,NaN,NaN,NaN
1661478,2023-10-01,79852.0,79104.0,0.945591,NaN,NaN
1661477,2023-11-01,77057.0,79852.0,-3.500225,NaN,NaN
1661476,2023-12-01,79753.0,77057.0,3.498709,NaN,NaN
1661475,2024-01-01,78761.0,79753.0,-1.243840,NaN,NaN
1661474,2024-02-01,77327.0,78761.0,-1.820698,NaN,NaN
1661473,2024-03-01,77362.0,77327.0,0.045262,NaN,NaN
1661472,2024-04-01,78590.0,77362.0,1.587343,NaN,NaN
1661471,2024-05-01,76123.0,78590.0,-3.139076,NaN,NaN
1661470,2024-06-01,76781.0,76123.0,0.864391,NaN,NaN
1661469,2024-07-01,76258.0,76781.0,-0.681158,NaN,NaN
1661468,2024-08-01,75274.0,76258.0,-1.290356,NaN,NaN
1661467,2024-09-01,74897.0,75274.0,-0.500837,79104.0,-5.318315
1661466,2024-10-01,74320.0,74897.0,-0.770391,79852.0,-6.927816
1661465,2024-11-01,73900.0,74320.0,-0.565124,77057.0,-4.096967
1661464,2024-12-01,73056.0,73900.0,-1.142084,79753.0,-8.397176
1661463,2025-01-01,72436.0,73056.0,-0.848664,78761.0,-8.030624
1661462,2025-02-01,72176.0,72436.0,-0.358938,77327.0,-6.661321
1661461,2025-03-01,71251.0,72176.0,-1.281589,77362.0,-7.899227
1661460,2025-04-01,70212.0,71251.0,-1.458225,78590.0,-10.660389
1661459,2025-05-01,70540.0,70212.0,0.467157,76123.0,-7.334183
1661458,2025-06-01,71188.0,70540.0,0.918628,76781.0,-7.284354
1661457,2025-07-01,71036.0,71188.0,-0.213519,76258.0,-6.847806
1661456,2025-08-01,70323.0,71036.0,-1.003716,75274.0,-6.577304
1661455,2025-09-01,70113.0,70323.0,-0.298622,74897.0,-6.387439
1661454,2025-10-01,69902.0,70113.0,-0.300943,74320.0,-5.944564
1661453,2025-11-01,69989.0,69902.0,0.124460,73900.0,-5.292287
1661452,2025-12-01,69249.0,69989.0,-1.057309,73056.0,-5.211071
1661451,2026-01-01,69420.0,69249.0,0.246935,72436.0,-4.163676
1661450,2026-02-01,69215.0,69420.0,-0.295304,72176.0,-4.102472
1661449,2026-03-01,68804.0,69215.0,-0.593802,71251.0,-3.434338
1661448,2026-04-01,68600.0,68804.0,-0.296494,70212.0,-2.295904
1661447,2026-05-01,68498.0,68600.0,-0.148688,70540.0,-2.894811
1661446,2026-06-01,69044.0,68498.0,0.797104,71188.0,-3.011744
1661445,2026-07-01,68492.0,69044.0,-0.799490,71036.0,-3.581283
1661444,2026-08-01,68652.0,68492.0,0.233604,70323.0,-2.376178
1661443,2026-09-01,67794.0,68652.0,-1.249782,70113.0,-3.307518
1661442,2026-10-01,67386.0,67794.0,-0.601823,69902.0,-3.599325

In [48]:
grupo = df_modelo.groupby(
    ["codigo_fipe", "ano_modelo"]
)

df_modelo["preco_proximo_mes"] = (
    grupo["preco"].shift(-1)
)

In [49]:
df_modelo["data_proximo_registro"] = (
    grupo["data_referencia"].shift(-1)
)

df_modelo["mes_esperado"] = (
    df_modelo["data_referencia"]
    + pd.offsets.MonthBegin(1)
)

df_modelo["target_valido"] = (
    df_modelo["data_proximo_registro"]
    == df_modelo["mes_esperado"]
)

In [50]:
df_modelo["target_valido"].value_counts()

target_valido
True     5428679
False     152873
Name: count, dtype: int64

In [51]:
df_modelo["target_valido"].value_counts(
    normalize=True
).mul(100).round(2)

target_valido
True     97.26
False     2.74
Name: proportion, dtype: float64

In [52]:
df_ml = df_modelo[
    df_modelo["target_valido"]
].copy()

In [53]:
df_ml[
    [
        "codigo_fipe",
        "nome_modelo",
        "ano_modelo",
        "data_referencia",
        "preco",
        "data_proximo_registro",
        "preco_proximo_mes"
    ]
].head(20)

,codigo_fipe,nome_modelo,ano_modelo,data_referencia,preco,data_proximo_registro,preco_proximo_mes
1760106,001001-4,Fiorino Furgão 1.5 mpi / i.e.,1992.0,2002-04-01,5746.0,2002-05-01,5758.0
1760105,001001-4,Fiorino Furgão 1.5 mpi / i.e.,1992.0,2002-05-01,5758.0,2002-06-01,5812.0
1760104,001001-4,Fiorino Furgão 1.5 mpi / i.e.,1992.0,2002-06-01,5812.0,2002-07-01,5983.0
1760103,001001-4,Fiorino Furgão 1.5 mpi / i.e.,1992.0,2002-07-01,5983.0,2002-08-01,6281.0
1760102,001001-4,Fiorino Furgão 1.5 mpi / i.e.,1992.0,2002-08-01,6281.0,2002-09-01,6127.0
1760101,001001-4,Fiorino Furgão 1.5 mpi / i.e.,1992.0,2002-09-01,6127.0,2002-10-01,6187.0
1760100,001001-4,Fiorino Furgão 1.5 mpi / i.e.,1992.0,2002-10-01,6187.0,2002-11-01,6133.0
1760099,001001-4,Fiorino Furgão 1.5 mpi / i.e.,1992.0,2002-11-01,6133.0,2002-12-01,6148.0
1760098,001001-4,Fiorino Furgão 1.5 mpi / i.e.,1992.0,2002-12-01,6148.0,2003-01-01,6160.0
1760097,001001-4,Fiorino Furgão 1.5 mpi / i.e.,1992.0,2003-01-01,6160.0,2003-02-01,6170.0
1760096,001001-4,Fiorino Furgão 1.5 mpi / i.e.,1992.0,2003-02-01,6170.0,2003-03-01,6117.0
1760095,001001-4,Fiorino Furgão 1.5 mpi / i.e.,1992.0,2003-03-01,6117.0,2003-04-01,6107.0
1760094,001001-4,Fiorino Furgão 1.5 mpi / i.e.,1992.0,2003-04-01,6107.0,2003-05-01,6100.0
1760093,001001-4,Fiorino Furgão 1.5 mpi / i.e.,1992.0,2003-05-01,6100.0,2003-06-01,6099.0
1760092,001001-4,Fiorino Furgão 1.5 mpi / i.e.,1992.0,2003-06-01,6099.0,2003-07-01,6101.0
1760091,001001-4,Fiorino Furgão 1.5 mpi / i.e.,1992.0,2003-07-01,6101.0,2003-08-01,6070.0
1760090,001001-4,Fiorino Furgão 1.5 mpi / i.e.,1992.0,2003-08-01,6070.0,2003-09-01,6074.0
1760089,001001-4,Fiorino Furgão 1.5 mpi / i.e.,1992.0,2003-09-01,6074.0,2003-10-01,6069.0
1760088,001001-4,Fiorino Furgão 1.5 mpi / i.e.,1992.0,2003-10-01,6069.0,2003-11-01,6056.0
1760087,001001-4,Fiorino Furgão 1.5 mpi / i.e.,1992.0,2003-11-01,6056.0,2003-12-01,6072.0

In [54]:
df_ml["mes"] = df_ml["data_referencia"].dt.month
df_ml["ano"] = df_ml["data_referencia"].dt.year

features = [
    "ano_modelo",
    "idade_veiculo",
    "mes",
    "ano",
    "preco",
    "preco_mes_anterior",
    "variacao_mensal_pct"
]

target = "preco_proximo_mes"

In [55]:
df_ml[features + [target]].isnull().sum()

ano_modelo                 0
idade_veiculo              0
mes                        0
ano                        0
preco                      0
preco_mes_anterior     28721
variacao_mensal_pct    28721
preco_proximo_mes          0
dtype: int64

In [56]:
df_ml_v1 = df_ml[
    features + [target, "data_referencia"]
].dropna().copy()

print(f"Registros disponíveis para ML: {len(df_ml_v1):,}")

Registros disponíveis para ML: 5,399,958

In [57]:
data_corte = pd.Timestamp("2025-01-01")

treino = df_ml_v1[
    df_ml_v1["data_referencia"] < data_corte
].copy()

teste = df_ml_v1[
    df_ml_v1["data_referencia"] >= data_corte
].copy()

print(f"Treino: {len(treino):,}")
print(f"Teste: {len(teste):,}")

print(
    f'Período treino: {treino["data_referencia"].min()} '
    f'até {treino["data_referencia"].max()}'
)

print(
    f'Período teste: {teste["data_referencia"].min()} '
    f'até {teste["data_referencia"].max()}'
)

Treino: 4,806,947
Teste: 593,011
Período treino: 2001-01-01 00:00:00 até 2024-12-01 00:00:00
Período teste: 2025-01-01 00:00:00 até 2026-09-01 00:00:00

In [58]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import numpy as np

# Baseline:
# preço previsto do próximo mês = preço do mês atual
teste["previsao_baseline"] = teste["preco"]

y_real = teste[target]
y_pred = teste["previsao_baseline"]

mae = mean_absolute_error(y_real, y_pred)

rmse = np.sqrt(
    mean_squared_error(y_real, y_pred)
)

r2 = r2_score(y_real, y_pred)

mape = (
    np.abs(
        (y_real - y_pred) / y_real
    ).mean() * 100
)

print("=" * 40)
print("BASELINE — PREÇO ATUAL")
print("=" * 40)

print(f"MAE:  R$ {mae:,.2f}")
print(f"RMSE: R$ {rmse:,.2f}")
print(f"R²:   {r2:.6f}")
print(f"MAPE: {mape:.4f}%")

========================================
BASELINE — PREÇO ATUAL
========================================
MAE:  R$ 1,557.91
RMSE: R$ 6,910.75
R²:   0.999695
MAPE: 1.2818%

In [59]:
features = [
    "ano_modelo",
    "idade_veiculo",
    "mes",
    "ano",
    "preco",
    "preco_mes_anterior",
    "variacao_mensal_pct"
]

target = "preco_proximo_mes"

In [60]:
X_train = treino[features]
y_train = treino[target]

X_test = teste[features]
y_test = teste[target]

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

X_train: (4806947, 7)
X_test: (593011, 7)

In [61]:
from sklearn.linear_model import LinearRegression

modelo_lr = LinearRegression()

modelo_lr.fit(X_train, y_train)

LinearRegression()

In [62]:
pred_lr = modelo_lr.predict(X_test)

In [63]:
mae_lr = mean_absolute_error(
    y_test,
    pred_lr
)

rmse_lr = np.sqrt(
    mean_squared_error(
        y_test,
        pred_lr
    )
)

r2_lr = r2_score(
    y_test,
    pred_lr
)

mape_lr = (
    np.abs(
        (y_test - pred_lr) / y_test
    ).mean() * 100
)

print("=" * 40)
print("LINEAR REGRESSION")
print("=" * 40)

print(f"MAE:  R$ {mae_lr:,.2f}")
print(f"RMSE: R$ {rmse_lr:,.2f}")
print(f"R²:   {r2_lr:.6f}")
print(f"MAPE: {mape_lr:.4f}%")

========================================
LINEAR REGRESSION
========================================
MAE:  R$ 1,572.26
RMSE: R$ 6,738.26
R²:   0.999710
MAPE: 1.7117%

In [64]:
teste["erro_baseline"] = (
    teste["preco_proximo_mes"]
    - teste["previsao_baseline"]
)

teste["erro_abs_baseline"] = (
    teste["erro_baseline"].abs()
)

teste["erro_pct_baseline"] = (
    teste["erro_abs_baseline"]
    / teste["preco_proximo_mes"]
) * 100

In [65]:
teste["erro_pct_baseline"].describe(
    percentiles=[0.50, 0.75, 0.90, 0.95, 0.99]
)

count    593011.000000
mean          1.281812
std           3.092816
min           0.000000
50%           0.506869
75%           1.648011
90%           3.380282
95%           3.627260
99%           5.264055
max         167.629165
Name: erro_pct_baseline, dtype: float64

In [66]:
grupo = df_modelo.groupby(
    ["codigo_fipe", "ano_modelo"]
)

df_modelo["variacao_3m_pct"] = (
    (
        df_modelo["preco"]
        / grupo["preco"].shift(3)
    ) - 1
) * 100

df_modelo["variacao_6m_pct"] = (
    (
        df_modelo["preco"]
        / grupo["preco"].shift(6)
    ) - 1
) * 100

In [67]:
df_modelo["media_3m"] = (
    grupo["preco"]
    .transform(
        lambda x: x.rolling(3).mean()
    )
)

df_modelo["media_6m"] = (
    grupo["preco"]
    .transform(
        lambda x: x.rolling(6).mean()
    )
)

In [68]:
df_modelo["variacao_proximo_mes_pct"] = (
    (
        df_modelo["preco_proximo_mes"]
        / df_modelo["preco"]
    ) - 1
) * 100

In [69]:
piores = (
    teste
    .sort_values("erro_pct_baseline", ascending=False)
    [
        [
            "codigo_fipe",
            "nome_marca",
            "nome_modelo",
            "ano_modelo",
            "data_referencia",
            "preco",
            "preco_proximo_mes",
            "erro_abs_baseline",
            "erro_pct_baseline"
        ]
    ]
    .head(20)
)

display(piores)

KeyError: "['codigo_fipe', 'nome_marca', 'nome_modelo'] not in index"

In [70]:
colunas_id = [
    "codigo_fipe",
    "nome_marca",
    "nome_modelo",
    "nome_combustivel"
]

df_ml_v1 = df_ml[
    colunas_id
    + features
    + [target, "data_referencia"]
].dropna(
    subset=features + [target]
).copy()

print(f"Registros: {len(df_ml_v1):,}")
print(df_ml_v1.columns.tolist())

Registros: 5,399,958
['codigo_fipe', 'nome_marca', 'nome_modelo', 'nome_combustivel', 'ano_modelo', 'idade_veiculo', 'mes', 'ano', 'preco', 'preco_mes_anterior', 'variacao_mensal_pct', 'preco_proximo_mes', 'data_referencia']

In [71]:
data_corte = pd.Timestamp("2025-01-01")

treino = df_ml_v1[
    df_ml_v1["data_referencia"] < data_corte
].copy()

teste = df_ml_v1[
    df_ml_v1["data_referencia"] >= data_corte
].copy()

print(f"Treino: {len(treino):,}")
print(f"Teste: {len(teste):,}")

Treino: 4,806,947
Teste: 593,011

In [72]:
teste["previsao_baseline"] = teste["preco"]

teste["erro_abs_baseline"] = (
    teste["preco_proximo_mes"]
    - teste["previsao_baseline"]
).abs()

teste["erro_pct_baseline"] = (
    teste["erro_abs_baseline"]
    / teste["preco_proximo_mes"]
) * 100

In [73]:
piores = (
    teste
    .sort_values(
        "erro_pct_baseline",
        ascending=False
    )
    [
        [
            "codigo_fipe",
            "nome_marca",
            "nome_modelo",
            "ano_modelo",
            "data_referencia",
            "preco",
            "preco_proximo_mes",
            "erro_abs_baseline",
            "erro_pct_baseline"
        ]
    ]
    .head(20)
)

display(piores)

,codigo_fipe,nome_marca,nome_modelo,ano_modelo,data_referencia,preco,preco_proximo_mes,erro_abs_baseline,erro_pct_baseline
8946583,005024-5,VW - VolksWagen,Kombi Standard/ Luxo/ Série Prata,1995.0,2026-08-01,27713.0,10355.0,17358.0,167.629165
8946581,005024-5,VW - VolksWagen,Kombi Standard/ Luxo/ Série Prata,1995.0,2026-09-01,27157.0,10240.0,16917.0,165.205078
8946585,005024-5,VW - VolksWagen,Kombi Standard/ Luxo/ Série Prata,1995.0,2026-07-01,27440.0,10373.0,17067.0,164.532922
8946603,005024-5,VW - VolksWagen,Kombi Standard/ Luxo/ Série Prata,1995.0,2025-10-01,27896.0,10572.0,17324.0,163.866818
8947201,005024-5,VW - VolksWagen,Kombi Standard/ Luxo/ Série Prata,1996.0,2026-09-01,27836.0,10969.0,16867.0,153.769715
2316224,003042-2,Ford,F-1000 Super 3.6 / Super Série 3.6,1995.0,2025-07-01,31564.0,12494.0,19070.0,152.633264
8919040,005023-7,VW - VolksWagen,Kombi Furgão,1995.0,2026-09-01,19448.0,7747.0,11701.0,151.039112
8947221,005024-5,VW - VolksWagen,Kombi Standard/ Luxo/ Série Prata,1996.0,2025-11-01,28022.0,11307.0,16715.0,147.828779
8919690,005023-7,VW - VolksWagen,Kombi Furgão,1996.0,2025-06-01,18354.0,7409.0,10945.0,147.725739
8947209,005024-5,VW - VolksWagen,Kombi Standard/ Luxo/ Série Prata,1996.0,2026-05-01,27575.0,11157.0,16418.0,147.154253
2316230,003042-2,Ford,F-1000 Super 3.6 / Super Série 3.6,1995.0,2025-04-01,31013.0,12554.0,18459.0,147.036801
8946613,005024-5,VW - VolksWagen,Kombi Standard/ Luxo/ Série Prata,1995.0,2025-05-01,26309.0,10685.0,15624.0,146.223678
2316232,003042-2,Ford,F-1000 Super 3.6 / Super Série 3.6,1995.0,2025-03-01,30707.0,12566.0,18141.0,144.365749
2316200,003042-2,Ford,F-1000 Super 3.6 / Super Série 3.6,1995.0,2026-07-01,32616.0,13365.0,19251.0,144.040404
8919052,005023-7,VW - VolksWagen,Kombi Furgão,1995.0,2026-03-01,19290.0,7908.0,11382.0,143.930197
8919054,005023-7,VW - VolksWagen,Kombi Furgão,1995.0,2026-02-01,19334.0,7936.0,11398.0,143.623992
2316202,003042-2,Ford,F-1000 Super 3.6 / Super Série 3.6,1995.0,2026-06-01,32471.0,13406.0,19065.0,142.212442
2316204,003042-2,Ford,F-1000 Super 3.6 / Super Série 3.6,1995.0,2026-05-01,32343.0,13419.0,18924.0,141.023921
8919056,005023-7,VW - VolksWagen,Kombi Furgão,1995.0,2026-01-01,19143.0,7954.0,11189.0,140.671360
2316208,003042-2,Ford,F-1000 Super 3.6 / Super Série 3.6,1995.0,2026-03-01,32322.0,13464.0,18858.0,140.062389

In [74]:
kombi = (
    df_modelo[
        (df_modelo["codigo_fipe"] == "005024-5") &
        (df_modelo["ano_modelo"] == 1995)
    ]
    .sort_values("data_referencia")
    .copy()
)

display(
    kombi[
        [
            "data_referencia",
            "preco",
            "preco_proximo_mes",
            "variacao_mensal_pct"
        ]
    ].tail(30)
)

        data_referencia    preco  preco_proximo_mes  variacao_mensal_pct
8946606      2025-08-01  10656.0            27105.0            -0.168634
8946607      2025-08-01  27105.0            27376.0           154.363739
8946604      2025-09-01  27376.0            10633.0             0.999816
8946605      2025-09-01  10633.0            10598.0           -61.159410
8946602      2025-10-01  10598.0            27896.0            -0.329164
8946603      2025-10-01  27896.0            10572.0           163.219475
8946601      2025-11-01  27338.0            27196.0           158.588725
8946600      2025-11-01  10572.0            27338.0           -62.102093
8946598      2025-12-01  27196.0            10556.0            -0.519424
8946599      2025-12-01  10556.0            10535.0           -61.185468
8946596      2026-01-01  10535.0            27053.0            -0.198939
8946597      2026-01-01  27053.0            27323.0           156.791647
8946594      2026-02-01  27323.0            10511.0             0.998041
8946595      2026-02-01  10511.0            27181.0           -61.530579
8946593      2026-03-01  10487.0            10450.0           -61.417902
8946592      2026-03-01  27181.0            10487.0           158.595757
8946591      2026-04-01  26637.0            26902.0           154.899522
8946590      2026-04-01  10450.0            26637.0            -0.352818
8946588      2026-05-01  26902.0            10435.0             0.994857
8946589      2026-05-01  10435.0            27170.0           -61.211062
8946586      2026-06-01  27170.0            10415.0           160.373742
8946587      2026-06-01  10415.0            10405.0           -61.667280
8946584      2026-07-01  10405.0            27440.0            -0.096015
8946585      2026-07-01  27440.0            10373.0           163.719366
8946582      2026-08-01  10373.0            27713.0           -62.197522
8946583      2026-08-01  27713.0            10355.0           167.164755
8946580      2026-09-01  10355.0            27157.0           -62.634865
8946581      2026-09-01  27157.0            10240.0           162.259778
8946578      2026-10-01  10240.0            27118.0           -62.293331
8946579      2026-10-01  27118.0                NaN           164.824219

In [75]:
kombi[
    kombi["data_referencia"].between(
        "2025-08-01",
        "2025-11-01"
    )
].sort_values(
    ["data_referencia", "preco"]
)

,tipo_veiculo,codigo_fipe,nome_modelo,nome_marca,nome_combustivel,sigla_combustivel,ano_modelo,zero_km,valor_centavos,valor_formatado,mes_referencia,ano_referencia,preco,data_referencia,preco_mes_anterior,variacao_mensal_pct,preco_12m_atras,variacao_12m_pct,idade_veiculo,idade_veiculo_raw,modelo_ano_futuro,preco_proximo_mes,data_proximo_registro,mes_esperado,target_valido,variacao_3m_pct,variacao_6m_pct,media_3m,media_6m,variacao_proximo_mes_pct
8946606,carro,005024-5,Kombi Standard/ Luxo/ Série Prata,VW - VolksWagen,Álcool,e,1995.0,False,1065600,"R$ 10.656,00",8,2025,10656.0,2025-08-01,10674.0,-0.168634,25287.0,-57.859770,30.0,30.0,0,27105.0,2025-08-01,2025-09-01,False,-59.897637,-0.476324,16055.666667,18622.166667,154.363739
8946607,carro,005024-5,Kombi Standard/ Luxo/ Série Prata,VW - VolksWagen,Gasolina,g,1995.0,False,2710500,"R$ 27.105,00",8,2025,27105.0,2025-08-01,10656.0,154.363739,9958.0,172.193211,30.0,30.0,0,27376.0,2025-09-01,2025-09-01,True,0.998621,3.025581,16145.000000,18754.833333,0.999816
8946605,carro,005024-5,Kombi Standard/ Luxo/ Série Prata,VW - VolksWagen,Álcool,e,1995.0,False,1063300,"R$ 10.633,00",9,2025,10633.0,2025-09-01,27376.0,-61.159410,10734.0,-0.940935,30.0,30.0,0,10598.0,2025-10-01,2025-10-01,True,-0.215841,-59.984194,21704.666667,18880.166667,-0.329164
8946604,carro,005024-5,Kombi Standard/ Luxo/ Série Prata,VW - VolksWagen,Gasolina,g,1995.0,False,2737600,"R$ 27.376,00",9,2025,27376.0,2025-09-01,27105.0,0.999816,25539.0,7.192921,30.0,30.0,0,10633.0,2025-09-01,2025-10-01,False,156.473674,156.209640,21712.333333,21536.666667,-61.159410
8946602,carro,005024-5,Kombi Standard/ Luxo/ Série Prata,VW - VolksWagen,Álcool,e,1995.0,False,1059800,"R$ 10.598,00",10,2025,10598.0,2025-10-01,10633.0,-0.329164,25794.0,-58.912925,30.0,30.0,0,27896.0,2025-10-01,2025-11-01,False,-60.900203,-60.509744,16202.333333,16173.666667,163.219475
8946603,carro,005024-5,Kombi Standard/ Luxo/ Série Prata,VW - VolksWagen,Gasolina,g,1995.0,False,2789600,"R$ 27.896,00",10,2025,27896.0,2025-10-01,10598.0,163.219475,10717.0,160.296725,30.0,30.0,0,10572.0,2025-11-01,2025-11-01,True,1.899474,161.345325,16375.666667,19044.000000,-62.102093
8946600,carro,005024-5,Kombi Standard/ Luxo/ Série Prata,VW - VolksWagen,Álcool,e,1995.0,False,1057200,"R$ 10.572,00",11,2025,10572.0,2025-11-01,27896.0,-62.102093,10707.0,-1.260857,30.0,30.0,0,27338.0,2025-11-01,2025-12-01,False,-0.573686,-0.788288,16355.333333,19030.000000,158.588725
8946601,carro,005024-5,Kombi Standard/ Luxo/ Série Prata,VW - VolksWagen,Gasolina,g,1995.0,False,2733800,"R$ 27.338,00",11,2025,27338.0,2025-11-01,10572.0,158.588725,26309.0,3.911209,30.0,30.0,0,27196.0,2025-12-01,2025-12-01,True,157.954331,0.859620,21935.333333,19068.833333,-0.519424

In [76]:
chave = [
    "codigo_fipe",
    "ano_modelo",
    "data_referencia"
]

duplicados_chave = (
    df_modelo
    .duplicated(
        subset=chave,
        keep=False
    )
)

print(
    f"Registros em chaves duplicadas: "
    f"{duplicados_chave.sum():,}"
)

print(
    f"Percentual: "
    f"{duplicados_chave.mean() * 100:.2f}%"
)

Registros em chaves duplicadas: 245,958
Percentual: 4.41%

In [77]:
display(
    kombi[
        kombi["data_referencia"].between(
            "2025-08-01",
            "2025-11-01"
        )
    ]
    .sort_values(
        ["data_referencia", "preco"]
    )
)

,tipo_veiculo,codigo_fipe,nome_modelo,nome_marca,nome_combustivel,sigla_combustivel,ano_modelo,zero_km,valor_centavos,valor_formatado,mes_referencia,ano_referencia,preco,data_referencia,preco_mes_anterior,variacao_mensal_pct,preco_12m_atras,variacao_12m_pct,idade_veiculo,idade_veiculo_raw,modelo_ano_futuro,preco_proximo_mes,data_proximo_registro,mes_esperado,target_valido,variacao_3m_pct,variacao_6m_pct,media_3m,media_6m,variacao_proximo_mes_pct
8946606,carro,005024-5,Kombi Standard/ Luxo/ Série Prata,VW - VolksWagen,Álcool,e,1995.0,False,1065600,"R$ 10.656,00",8,2025,10656.0,2025-08-01,10674.0,-0.168634,25287.0,-57.859770,30.0,30.0,0,27105.0,2025-08-01,2025-09-01,False,-59.897637,-0.476324,16055.666667,18622.166667,154.363739
8946607,carro,005024-5,Kombi Standard/ Luxo/ Série Prata,VW - VolksWagen,Gasolina,g,1995.0,False,2710500,"R$ 27.105,00",8,2025,27105.0,2025-08-01,10656.0,154.363739,9958.0,172.193211,30.0,30.0,0,27376.0,2025-09-01,2025-09-01,True,0.998621,3.025581,16145.000000,18754.833333,0.999816
8946605,carro,005024-5,Kombi Standard/ Luxo/ Série Prata,VW - VolksWagen,Álcool,e,1995.0,False,1063300,"R$ 10.633,00",9,2025,10633.0,2025-09-01,27376.0,-61.159410,10734.0,-0.940935,30.0,30.0,0,10598.0,2025-10-01,2025-10-01,True,-0.215841,-59.984194,21704.666667,18880.166667,-0.329164
8946604,carro,005024-5,Kombi Standard/ Luxo/ Série Prata,VW - VolksWagen,Gasolina,g,1995.0,False,2737600,"R$ 27.376,00",9,2025,27376.0,2025-09-01,27105.0,0.999816,25539.0,7.192921,30.0,30.0,0,10633.0,2025-09-01,2025-10-01,False,156.473674,156.209640,21712.333333,21536.666667,-61.159410
8946602,carro,005024-5,Kombi Standard/ Luxo/ Série Prata,VW - VolksWagen,Álcool,e,1995.0,False,1059800,"R$ 10.598,00",10,2025,10598.0,2025-10-01,10633.0,-0.329164,25794.0,-58.912925,30.0,30.0,0,27896.0,2025-10-01,2025-11-01,False,-60.900203,-60.509744,16202.333333,16173.666667,163.219475
8946603,carro,005024-5,Kombi Standard/ Luxo/ Série Prata,VW - VolksWagen,Gasolina,g,1995.0,False,2789600,"R$ 27.896,00",10,2025,27896.0,2025-10-01,10598.0,163.219475,10717.0,160.296725,30.0,30.0,0,10572.0,2025-11-01,2025-11-01,True,1.899474,161.345325,16375.666667,19044.000000,-62.102093
8946600,carro,005024-5,Kombi Standard/ Luxo/ Série Prata,VW - VolksWagen,Álcool,e,1995.0,False,1057200,"R$ 10.572,00",11,2025,10572.0,2025-11-01,27896.0,-62.102093,10707.0,-1.260857,30.0,30.0,0,27338.0,2025-11-01,2025-12-01,False,-0.573686,-0.788288,16355.333333,19030.000000,158.588725
8946601,carro,005024-5,Kombi Standard/ Luxo/ Série Prata,VW - VolksWagen,Gasolina,g,1995.0,False,2733800,"R$ 27.338,00",11,2025,27338.0,2025-11-01,10572.0,158.588725,26309.0,3.911209,30.0,30.0,0,27196.0,2025-12-01,2025-12-01,True,157.954331,0.859620,21935.333333,19068.833333,-0.519424

In [78]:
chave = [
    "codigo_fipe",
    "ano_modelo",
    "data_referencia"
]

qtd_por_chave = (
    df_modelo
    .groupby(chave)
    .size()
)

display(
    qtd_por_chave
    .value_counts()
    .sort_index()
)

1    5335594
2     122979
Name: count, dtype: int64

In [79]:
precos_por_chave = (
    df_modelo
    .groupby(chave)["preco"]
    .nunique()
)

print(
    "Total de chaves:",
    f"{len(precos_por_chave):,}"
)

print(
    "Chaves com 1 preço:",
    f"{(precos_por_chave == 1).sum():,}"
)

print(
    "Chaves com preços diferentes:",
    f"{(precos_por_chave > 1).sum():,}"
)

print(
    "Percentual de conflitos:",
    f"{(precos_por_chave > 1).mean() * 100:.2f}%"
)

Total de chaves: 5,458,573
Chaves com 1 preço: 5,336,161
Chaves com preços diferentes: 122,412
Percentual de conflitos: 2.24%

In [80]:
for coluna in [
    "nome_combustivel",
    "sigla_combustivel",
    "nome_modelo",
    "nome_marca"
]:
    
    chave_teste = chave + [coluna]

    qtd = df_modelo.duplicated(
        subset=chave_teste,
        keep=False
    ).sum()

    print(
        f"{coluna:20} → {qtd:,} registros duplicados"
    )

nome_combustivel     → 28 registros duplicados
sigla_combustivel    → 28 registros duplicados
nome_modelo          → 245,950 registros duplicados
nome_marca           → 245,938 registros duplicados

In [81]:
conflitos = df_modelo[
    df_modelo.duplicated(
        subset=chave,
        keep=False
    )
].copy()

colunas_verificar = [
    "tipo_veiculo",
    "nome_modelo",
    "nome_marca",
    "nome_combustivel",
    "sigla_combustivel",
    "zero_km",
    "preco"
]

for coluna in colunas_verificar:
    
    qtd_variacao = (
        conflitos
        .groupby(chave)[coluna]
        .nunique(dropna=False)
        .gt(1)
        .sum()
    )
    
    print(
        f"{coluna:20} → "
        f"{qtd_variacao:,} chaves com valores diferentes"
    )

tipo_veiculo         → 0 chaves com valores diferentes
nome_modelo          → 4 chaves com valores diferentes
nome_marca           → 10 chaves com valores diferentes
nome_combustivel     → 122,965 chaves com valores diferentes
sigla_combustivel    → 122,965 chaves com valores diferentes
zero_km              → 0 chaves com valores diferentes
preco                → 122,412 chaves com valores diferentes

In [82]:
chave_correta = [
    "codigo_fipe",
    "ano_modelo",
    "sigla_combustivel",
    "data_referencia"
]

restantes = df_modelo[
    df_modelo.duplicated(
        subset=chave_correta,
        keep=False
    )
].sort_values(chave_correta)

print(f"Registros restantes: {len(restantes):,}")

display(
    restantes[
        [
            "codigo_fipe",
            "nome_marca",
            "nome_modelo",
            "ano_modelo",
            "nome_combustivel",
            "sigla_combustivel",
            "data_referencia",
            "preco"
        ]
    ]
)

Registros restantes: 28

,codigo_fipe,nome_marca,nome_modelo,ano_modelo,nome_combustivel,sigla_combustivel,data_referencia,preco
4755656,033182-1,Land Rover,Range.R. SP.HSE Dyn.BL. 2.0 Si4(Hibrido),2021.0,Híbrido,h,2021-11-01,612398.0
4755739,033182-1,Land Rover,Range.R. Sp.HSE Dyn.Bi. 2.0 Si4(Hibrido),2021.0,Híbrido,h,2021-11-01,612398.0
4755718,033182-1,Land Rover,Range.R. SP.HSE Dyn.BL. 2.0 Si4(Hibrido),2022.0,Híbrido,h,2021-11-01,642270.0
4755746,033182-1,Land Rover,Range.R. Sp.HSE Dyn.Bi. 2.0 Si4(Hibrido),2022.0,Híbrido,h,2021-11-01,642270.0
797653,040001-7,Baby,Buggy 1.6 2-Lug.,1988.0,Gasolina,g,2021-01-01,2216.0
808505,040001-7,Buggy,Buggy 1.6 2-Lug.,1988.0,Gasolina,g,2021-01-01,2216.0
797755,040001-7,Baby,Buggy 1.6 2-Lug.,1989.0,Gasolina,g,2021-01-01,2814.0
808714,040001-7,Buggy,Buggy 1.6 2-Lug.,1989.0,Gasolina,g,2021-01-01,2814.0
797857,040001-7,Baby,Buggy 1.6 2-Lug.,1990.0,Gasolina,g,2021-01-01,3228.0
808923,040001-7,Buggy,Buggy 1.6 2-Lug.,1990.0,Gasolina,g,2021-01-01,3228.0
797959,040001-7,Baby,Buggy 1.6 2-Lug.,1991.0,Gasolina,g,2021-01-01,3363.0
809132,040001-7,Buggy,Buggy 1.6 2-Lug.,1991.0,Gasolina,g,2021-01-01,3363.0
798061,040001-7,Baby,Buggy 1.6 2-Lug.,1992.0,Gasolina,g,2021-01-01,3469.0
809341,040001-7,Buggy,Buggy 1.6 2-Lug.,1992.0,Gasolina,g,2021-01-01,3469.0
798163,040001-7,Baby,Buggy 1.6 2-Lug.,1993.0,Gasolina,g,2021-01-01,3728.0
809550,040001-7,Buggy,Buggy 1.6 2-Lug.,1993.0,Gasolina,g,2021-01-01,3728.0
798265,040001-7,Baby,Buggy 1.6 2-Lug.,1994.0,Gasolina,g,2021-01-01,3852.0
809759,040001-7,Buggy,Buggy 1.6 2-Lug.,1994.0,Gasolina,g,2021-01-01,3852.0
798367,040001-7,Baby,Buggy 1.6 2-Lug.,1995.0,Gasolina,g,2021-01-01,4009.0
809968,040001-7,Buggy,Buggy 1.6 2-Lug.,1995.0,Gasolina,g,2021-01-01,4009.0
798469,040001-7,Baby,Buggy 1.6 2-Lug.,1996.0,Gasolina,g,2021-01-01,4473.0
810177,040001-7,Buggy,Buggy 1.6 2-Lug.,1996.0,Gasolina,g,2021-01-01,4473.0
798571,040001-7,Baby,Buggy 1.6 2-Lug.,1997.0,Gasolina,g,2021-01-01,4639.0
810386,040001-7,Buggy,Buggy 1.6 2-Lug.,1997.0,Gasolina,g,2021-01-01,4639.0
6994211,087007-2,Rolls-Royce,Cullinan Black Badge 6.7 V12 Aut.,2021.0,Gasolina,g,2021-11-01,5987963.0
6994359,087007-2,Rolls-Royce,CullinanBlack Badged 6.7 V12 Aut.,2021.0,Gasolina,g,2021-11-01,5987963.0
6994271,087007-2,Rolls-Royce,Cullinan Black Badge 6.7 V12 Aut.,2022.0,Gasolina,g,2021-11-01,6202120.0
6994364,087007-2,Rolls-Royce,CullinanBlack Badged 6.7 V12 Aut.,2022.0,Gasolina,g,2021-11-01,6202120.0

In [83]:
colunas_serie = [
    "codigo_fipe",
    "ano_modelo",
    "sigla_combustivel"
]

df_modelo = df_modelo.sort_values(
    colunas_serie + ["data_referencia"]
)

grupo = df_modelo.groupby(
    colunas_serie,
    sort=False
)

In [84]:
df_modelo["preco_mes_anterior"] = (
    grupo["preco"].shift(1)
)

df_modelo["variacao_mensal_pct"] = (
    (df_modelo["preco"] /
     df_modelo["preco_mes_anterior"] - 1) * 100
)

df_modelo["preco_12m_atras"] = (
    grupo["preco"].shift(12)
)

df_modelo["variacao_12m_pct"] = (
    (df_modelo["preco"] /
     df_modelo["preco_12m_atras"] - 1) * 100
)

df_modelo["preco_proximo_mes"] = (
    grupo["preco"].shift(-1)
)

df_modelo["data_proximo_registro"] = (
    grupo["data_referencia"].shift(-1)
)

In [85]:
# Chave que descobrimos como correta
chave_correta = [
    "codigo_fipe",
    "ano_modelo",
    "sigla_combustivel",
    "data_referencia"
]

# Selecionar somente os registros que ainda estão duplicados
restantes = df_modelo[
    df_modelo.duplicated(
        subset=chave_correta,
        keep=False
    )
].copy()

# Ordenar para facilitar a comparação
restantes = restantes.sort_values(chave_correta)

print(f"Quantidade de registros: {len(restantes)}")

display(
    restantes[
        [
            "codigo_fipe",
            "nome_marca",
            "nome_modelo",
            "ano_modelo",
            "nome_combustivel",
            "sigla_combustivel",
            "data_referencia",
            "preco"
        ]
    ]
)

Quantidade de registros: 28

,codigo_fipe,nome_marca,nome_modelo,ano_modelo,nome_combustivel,sigla_combustivel,data_referencia,preco
4755656,033182-1,Land Rover,Range.R. SP.HSE Dyn.BL. 2.0 Si4(Hibrido),2021.0,Híbrido,h,2021-11-01,612398.0
4755739,033182-1,Land Rover,Range.R. Sp.HSE Dyn.Bi. 2.0 Si4(Hibrido),2021.0,Híbrido,h,2021-11-01,612398.0
4755718,033182-1,Land Rover,Range.R. SP.HSE Dyn.BL. 2.0 Si4(Hibrido),2022.0,Híbrido,h,2021-11-01,642270.0
4755746,033182-1,Land Rover,Range.R. Sp.HSE Dyn.Bi. 2.0 Si4(Hibrido),2022.0,Híbrido,h,2021-11-01,642270.0
797653,040001-7,Baby,Buggy 1.6 2-Lug.,1988.0,Gasolina,g,2021-01-01,2216.0
808505,040001-7,Buggy,Buggy 1.6 2-Lug.,1988.0,Gasolina,g,2021-01-01,2216.0
797755,040001-7,Baby,Buggy 1.6 2-Lug.,1989.0,Gasolina,g,2021-01-01,2814.0
808714,040001-7,Buggy,Buggy 1.6 2-Lug.,1989.0,Gasolina,g,2021-01-01,2814.0
797857,040001-7,Baby,Buggy 1.6 2-Lug.,1990.0,Gasolina,g,2021-01-01,3228.0
808923,040001-7,Buggy,Buggy 1.6 2-Lug.,1990.0,Gasolina,g,2021-01-01,3228.0
797959,040001-7,Baby,Buggy 1.6 2-Lug.,1991.0,Gasolina,g,2021-01-01,3363.0
809132,040001-7,Buggy,Buggy 1.6 2-Lug.,1991.0,Gasolina,g,2021-01-01,3363.0
798061,040001-7,Baby,Buggy 1.6 2-Lug.,1992.0,Gasolina,g,2021-01-01,3469.0
809341,040001-7,Buggy,Buggy 1.6 2-Lug.,1992.0,Gasolina,g,2021-01-01,3469.0
798163,040001-7,Baby,Buggy 1.6 2-Lug.,1993.0,Gasolina,g,2021-01-01,3728.0
809550,040001-7,Buggy,Buggy 1.6 2-Lug.,1993.0,Gasolina,g,2021-01-01,3728.0
798265,040001-7,Baby,Buggy 1.6 2-Lug.,1994.0,Gasolina,g,2021-01-01,3852.0
809759,040001-7,Buggy,Buggy 1.6 2-Lug.,1994.0,Gasolina,g,2021-01-01,3852.0
798367,040001-7,Baby,Buggy 1.6 2-Lug.,1995.0,Gasolina,g,2021-01-01,4009.0
809968,040001-7,Buggy,Buggy 1.6 2-Lug.,1995.0,Gasolina,g,2021-01-01,4009.0
798469,040001-7,Baby,Buggy 1.6 2-Lug.,1996.0,Gasolina,g,2021-01-01,4473.0
810177,040001-7,Buggy,Buggy 1.6 2-Lug.,1996.0,Gasolina,g,2021-01-01,4473.0
798571,040001-7,Baby,Buggy 1.6 2-Lug.,1997.0,Gasolina,g,2021-01-01,4639.0
810386,040001-7,Buggy,Buggy 1.6 2-Lug.,1997.0,Gasolina,g,2021-01-01,4639.0
6994211,087007-2,Rolls-Royce,Cullinan Black Badge 6.7 V12 Aut.,2021.0,Gasolina,g,2021-11-01,5987963.0
6994359,087007-2,Rolls-Royce,CullinanBlack Badged 6.7 V12 Aut.,2021.0,Gasolina,g,2021-11-01,5987963.0
6994271,087007-2,Rolls-Royce,Cullinan Black Badge 6.7 V12 Aut.,2022.0,Gasolina,g,2021-11-01,6202120.0
6994364,087007-2,Rolls-Royce,CullinanBlack Badged 6.7 V12 Aut.,2022.0,Gasolina,g,2021-11-01,6202120.0

In [86]:
verificacao = (
    restantes
    .groupby(chave_correta)
    .agg(
        qtd_registros=("preco", "size"),
        qtd_precos=("preco", "nunique"),
        preco_min=("preco", "min"),
        preco_max=("preco", "max")
    )
)

display(verificacao)

                                                          qtd_registros  \
codigo_fipe ano_modelo sigla_combustivel data_referencia
033182-1    2021.0     h                 2021-11-01                   2
            2022.0     h                 2021-11-01                   2
040001-7    1988.0     g                 2021-01-01                   2
            1989.0     g                 2021-01-01                   2
            1990.0     g                 2021-01-01                   2
            1991.0     g                 2021-01-01                   2
            1992.0     g                 2021-01-01                   2
            1993.0     g                 2021-01-01                   2
            1994.0     g                 2021-01-01                   2
            1995.0     g                 2021-01-01                   2
            1996.0     g                 2021-01-01                   2
            1997.0     g                 2021-01-01                   2
087007-2    2021.0     g                 2021-11-01                   2
            2022.0     g                 2021-11-01                   2

                                                          qtd_precos  \
codigo_fipe ano_modelo sigla_combustivel data_referencia
033182-1    2021.0     h                 2021-11-01                1
            2022.0     h                 2021-11-01                1
040001-7    1988.0     g                 2021-01-01                1
            1989.0     g                 2021-01-01                1
            1990.0     g                 2021-01-01                1
            1991.0     g                 2021-01-01                1
            1992.0     g                 2021-01-01                1
            1993.0     g                 2021-01-01                1
            1994.0     g                 2021-01-01                1
            1995.0     g                 2021-01-01                1
            1996.0     g                 2021-01-01                1
            1997.0     g                 2021-01-01                1
087007-2    2021.0     g                 2021-11-01                1
            2022.0     g                 2021-11-01                1

                                                          preco_min  preco_max
codigo_fipe ano_modelo sigla_combustivel data_referencia
033182-1    2021.0     h                 2021-11-01        612398.0   612398.0
            2022.0     h                 2021-11-01        642270.0   642270.0
040001-7    1988.0     g                 2021-01-01          2216.0     2216.0
            1989.0     g                 2021-01-01          2814.0     2814.0
            1990.0     g                 2021-01-01          3228.0     3228.0
            1991.0     g                 2021-01-01          3363.0     3363.0
            1992.0     g                 2021-01-01          3469.0     3469.0
            1993.0     g                 2021-01-01          3728.0     3728.0
            1994.0     g                 2021-01-01          3852.0     3852.0
            1995.0     g                 2021-01-01          4009.0     4009.0
            1996.0     g                 2021-01-01          4473.0     4473.0
            1997.0     g                 2021-01-01          4639.0     4639.0
087007-2    2021.0     g                 2021-11-01       5987963.0  5987963.0
            2022.0     g                 2021-11-01       6202120.0  6202120.0

In [87]:
(verificacao["qtd_precos"] > 1).sum()

np.int64(0)

In [88]:
df_modelo_limpo = (
    df_modelo
    .sort_values(chave_correta)
    .drop_duplicates(
        subset=chave_correta,
        keep="first"
    )
    .copy()
)

print(f"Antes:  {len(df_modelo):,}")
print(f"Depois: {len(df_modelo_limpo):,}")
print(f"Removidos: {len(df_modelo) - len(df_modelo_limpo):,}")

Antes:  5,581,552
Depois: 5,581,538
Removidos: 14

In [89]:
qtd_duplicados = (
    df_modelo_limpo
    .duplicated(
        subset=chave_correta,
        keep=False
    )
    .sum()
)

print(f"Duplicados restantes: {qtd_duplicados:,}")

Duplicados restantes: 0

In [90]:
colunas_serie = [
    "codigo_fipe",
    "ano_modelo",
    "sigla_combustivel"
]

df_modelo_limpo = (
    df_modelo_limpo
    .sort_values(
        colunas_serie + ["data_referencia"]
    )
    .copy()
)

grupo = df_modelo_limpo.groupby(
    colunas_serie,
    sort=False
)

In [91]:
# Mês anterior
df_modelo_limpo["preco_mes_anterior"] = (
    grupo["preco"].shift(1)
)

df_modelo_limpo["data_mes_anterior"] = (
    grupo["data_referencia"].shift(1)
)

# Variação mensal
df_modelo_limpo["variacao_mensal_pct"] = (
    (
        df_modelo_limpo["preco"]
        / df_modelo_limpo["preco_mes_anterior"]
    ) - 1
) * 100

In [92]:
df_modelo_limpo["mes_anterior_esperado"] = (
    df_modelo_limpo["data_referencia"]
    - pd.offsets.MonthBegin(1)
)

df_modelo_limpo["mes_anterior_valido"] = (
    df_modelo_limpo["data_mes_anterior"]
    == df_modelo_limpo["mes_anterior_esperado"]
)

df_modelo_limpo.loc[
    ~df_modelo_limpo["mes_anterior_valido"],
    "variacao_mensal_pct"
] = np.nan

In [93]:
df_modelo_limpo["preco_proximo_mes"] = (
    grupo["preco"].shift(-1)
)

df_modelo_limpo["data_proximo_registro"] = (
    grupo["data_referencia"].shift(-1)
)

df_modelo_limpo["mes_esperado"] = (
    df_modelo_limpo["data_referencia"]
    + pd.offsets.MonthBegin(1)
)

df_modelo_limpo["target_valido"] = (
    df_modelo_limpo["data_proximo_registro"]
    == df_modelo_limpo["mes_esperado"]
)

In [94]:
df_modelo_limpo["target_valido"].value_counts()

target_valido
True     5551074
False      30464
Name: count, dtype: int64

In [95]:
df_modelo_limpo["target_valido"].value_counts(
    normalize=True
).mul(100).round(2)

target_valido
True     99.45
False     0.55
Name: proportion, dtype: float64

In [96]:
kombi_corrigida = df_modelo_limpo[
    (df_modelo_limpo["codigo_fipe"] == "005024-5") &
    (df_modelo_limpo["ano_modelo"] == 1995)
][
    [
        "data_referencia",
        "nome_combustivel",
        "sigla_combustivel",
        "preco",
        "preco_mes_anterior",
        "variacao_mensal_pct"
    ]
].sort_values(
    ["sigla_combustivel", "data_referencia"]
)

display(
    kombi_corrigida[
        kombi_corrigida["data_referencia"] >= "2025-08-01"
    ].head(20)
)

,data_referencia,nome_combustivel,sigla_combustivel,preco,preco_mes_anterior,variacao_mensal_pct
8946606,2025-08-01,Álcool,e,10656.0,10674.0,-0.168634
8946605,2025-09-01,Álcool,e,10633.0,10656.0,-0.215841
8946602,2025-10-01,Álcool,e,10598.0,10633.0,-0.329164
8946600,2025-11-01,Álcool,e,10572.0,10598.0,-0.245329
8946599,2025-12-01,Álcool,e,10556.0,10572.0,-0.151343
8946596,2026-01-01,Álcool,e,10535.0,10556.0,-0.198939
8946595,2026-02-01,Álcool,e,10511.0,10535.0,-0.227812
8946593,2026-03-01,Álcool,e,10487.0,10511.0,-0.228332
8946590,2026-04-01,Álcool,e,10450.0,10487.0,-0.352818
8946589,2026-05-01,Álcool,e,10435.0,10450.0,-0.143541
8946587,2026-06-01,Álcool,e,10415.0,10435.0,-0.191663
8946584,2026-07-01,Álcool,e,10405.0,10415.0,-0.096015
8946582,2026-08-01,Álcool,e,10373.0,10405.0,-0.307544
8946580,2026-09-01,Álcool,e,10355.0,10373.0,-0.173527
8946578,2026-10-01,Álcool,e,10240.0,10355.0,-1.110575
8946607,2025-08-01,Gasolina,g,27105.0,26837.0,0.998621
8946604,2025-09-01,Gasolina,g,27376.0,27105.0,0.999816
8946603,2025-10-01,Gasolina,g,27896.0,27376.0,1.899474
8946601,2025-11-01,Gasolina,g,27338.0,27896.0,-2.000287
8946598,2025-12-01,Gasolina,g,27196.0,27338.0,-0.519424

In [97]:
df_ml_corrigido = df_modelo_limpo[
    df_modelo_limpo["target_valido"]
].copy()

print(f"Registros com target válido: {len(df_ml_corrigido):,}")

Registros com target válido: 5,551,074

In [98]:
df_ml_corrigido["mes"] = (
    df_ml_corrigido["data_referencia"].dt.month
)

df_ml_corrigido["ano"] = (
    df_ml_corrigido["data_referencia"].dt.year
)

features = [
    "ano_modelo",
    "idade_veiculo",
    "mes",
    "ano",
    "preco",
    "preco_mes_anterior",
    "variacao_mensal_pct"
]

target = "preco_proximo_mes"

In [99]:
df_ml_v2 = df_ml_corrigido.dropna(
    subset=features + [target]
).copy()

print(f"Registros disponíveis para ML: {len(df_ml_v2):,}")

Registros disponíveis para ML: 5,521,126

In [100]:
data_corte = pd.Timestamp("2025-01-01")

treino_v2 = df_ml_v2[
    df_ml_v2["data_referencia"] < data_corte
].copy()

teste_v2 = df_ml_v2[
    df_ml_v2["data_referencia"] >= data_corte
].copy()

print(f"Treino: {len(treino_v2):,}")
print(f"Teste:  {len(teste_v2):,}")

Treino: 4,919,210
Teste:  601,916

In [101]:
teste_v2["previsao_baseline"] = teste_v2["preco"]

y_real_v2 = teste_v2[target]
y_pred_v2 = teste_v2["previsao_baseline"]

mae_v2 = mean_absolute_error(
    y_real_v2,
    y_pred_v2
)

rmse_v2 = np.sqrt(
    mean_squared_error(
        y_real_v2,
        y_pred_v2
    )
)

r2_v2 = r2_score(
    y_real_v2,
    y_pred_v2
)

mape_v2 = (
    np.abs(
        (y_real_v2 - y_pred_v2) / y_real_v2
    ).mean() * 100
)

print("=" * 45)
print("BASELINE — SÉRIE CORRIGIDA")
print("=" * 45)

print(f"MAE:  R$ {mae_v2:,.2f}")
print(f"RMSE: R$ {rmse_v2:,.2f}")
print(f"R²:   {r2_v2:.6f}")
print(f"MAPE: {mape_v2:.4f}%")

=============================================
BASELINE — SÉRIE CORRIGIDA
=============================================
MAE:  R$ 1,513.27
RMSE: R$ 6,845.60
R²:   0.999696
MAPE: 1.1097%

In [102]:
comparacao = pd.DataFrame({
    "Modelo": [
        "Baseline - chave antiga",
        "Baseline - chave corrigida"
    ],
    "MAE": [
        1557.91,
        mae_v2
    ],
    "RMSE": [
        6910.75,
        rmse_v2
    ],
    "R2": [
        0.999695,
        r2_v2
    ],
    "MAPE": [
        1.2818,
        mape_v2
    ]
})

display(comparacao)

                       Modelo          MAE         RMSE        R2     MAPE
0     Baseline - chave antiga  1557.910000  6910.750000  0.999695  1.28180
1  Baseline - chave corrigida  1513.271888  6845.603989  0.999696  1.10967

In [103]:
grupo = df_modelo_limpo.groupby(
    [
        "codigo_fipe",
        "ano_modelo",
        "sigla_combustivel"
    ],
    sort=False
)

for lag in [3, 6, 12]:

    df_modelo_limpo[f"preco_{lag}m_atras"] = (
        grupo["preco"].shift(lag)
    )

    df_modelo_limpo[f"data_{lag}m_atras"] = (
        grupo["data_referencia"].shift(lag)
    )

In [104]:
for lag in [3, 6, 12]:

    data_esperada = (
        df_modelo_limpo["data_referencia"]
        - pd.DateOffset(months=lag)
    )

    valido = (
        df_modelo_limpo[f"data_{lag}m_atras"]
        == data_esperada
    )

    df_modelo_limpo[f"variacao_{lag}m_pct"] = np.where(
        valido,
        (
            df_modelo_limpo["preco"]
            / df_modelo_limpo[f"preco_{lag}m_atras"]
            - 1
        ) * 100,
        np.nan
    )

In [105]:
display(
    df_modelo_limpo[
        [
            "variacao_mensal_pct",
            "variacao_3m_pct",
            "variacao_6m_pct",
            "variacao_12m_pct"
        ]
    ].describe().round(2)
)

       variacao_mensal_pct  variacao_3m_pct  variacao_6m_pct  variacao_12m_pct
count           5551074.00       5491318.00       5402513.00        5226758.00
mean                 -0.14            -0.40            -0.76             -1.39
std                   1.67             3.40             5.61              9.48
min                 -46.31           -48.35           -54.22            -60.37
25%                  -0.78            -1.99            -3.53             -6.32
50%                  -0.23            -0.72            -1.39             -2.69
75%                   0.45             0.93             1.29              1.83
max                 110.46           117.68           128.22            168.93

In [106]:
for coluna in [
    "variacao_mensal_pct",
    "variacao_3m_pct",
    "variacao_6m_pct",
    "variacao_12m_pct"
]:

    qtd = df_modelo_limpo[coluna].notna().sum()
    pct = qtd / len(df_modelo_limpo) * 100

    print(
        f"{coluna:22} "
        f"{qtd:>10,} registros "
        f"({pct:.2f}%)"
    )

variacao_mensal_pct     5,551,074 registros (99.45%)
variacao_3m_pct         5,491,318 registros (98.38%)
variacao_6m_pct         5,402,513 registros (96.79%)
variacao_12m_pct        5,226,758 registros (93.64%)

In [107]:
df_modelo_limpo["target_variacao_proximo_mes"] = np.where(
    df_modelo_limpo["target_valido"],
    (
        df_modelo_limpo["preco_proximo_mes"]
        / df_modelo_limpo["preco"]
        - 1
    ) * 100,
    np.nan
)

In [108]:
display(
    df_modelo_limpo[
        "target_variacao_proximo_mes"
    ].describe(
        percentiles=[
            0.01,
            0.05,
            0.25,
            0.50,
            0.75,
            0.95,
            0.99
        ]
    ).round(3)
)

count    5551074.000
mean          -0.143
std            1.669
min          -46.309
1%            -3.946
5%            -2.785
25%           -0.785
50%           -0.232
75%            0.450
95%            2.788
99%            4.899
max          110.459
Name: target_variacao_proximo_mes, dtype: float64

In [109]:
qtd_target = (
    df_modelo_limpo[
        "target_variacao_proximo_mes"
    ]
    .notna()
    .sum()
)

pct_target = qtd_target / len(df_modelo_limpo) * 100

print(f"Targets disponíveis: {qtd_target:,}")
print(f"Cobertura: {pct_target:.2f}%")

Targets disponíveis: 5,551,074
Cobertura: 99.45%

In [110]:
features_v2 = [
    "idade_veiculo",
    "preco",
    "variacao_mensal_pct",
    "variacao_3m_pct",
    "variacao_6m_pct",
    "variacao_12m_pct",
    "mes"
]

target_v2 = "target_variacao_proximo_mes"

In [111]:
df_modelo_limpo["mes"] = (
    df_modelo_limpo["data_referencia"].dt.month
)

In [112]:
df_ml_v2 = df_modelo_limpo[
    [
        "codigo_fipe",
        "nome_marca",
        "nome_modelo",
        "sigla_combustivel",
        "ano_modelo",
        "data_referencia"
    ]
    + features_v2
    + [target_v2]
].dropna(
    subset=features_v2 + [target_v2]
).copy()

print(f"Registros ML V2: {len(df_ml_v2):,}")

Registros ML V2: 5,197,641

In [113]:
data_corte = pd.Timestamp("2025-01-01")

treino_v2 = df_ml_v2[
    df_ml_v2["data_referencia"] < data_corte
].copy()

teste_v2 = df_ml_v2[
    df_ml_v2["data_referencia"] >= data_corte
].copy()

print(f"Treino V2: {len(treino_v2):,}")
print(f"Teste V2:  {len(teste_v2):,}")

print(
    "Treino:",
    treino_v2["data_referencia"].min(),
    "até",
    treino_v2["data_referencia"].max()
)

print(
    "Teste:",
    teste_v2["data_referencia"].min(),
    "até",
    teste_v2["data_referencia"].max()
)

Treino V2: 4,612,211
Teste V2:  585,430
Treino: 2002-01-01 00:00:00 até 2024-12-01 00:00:00
Teste: 2025-01-01 00:00:00 até 2026-09-01 00:00:00

In [114]:
teste_v2["pred_variacao_zero"] = 0.0

In [115]:
teste_v2["pred_variacao_tendencia"] = (
    teste_v2["variacao_mensal_pct"]
)

In [116]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

y_real = teste_v2[target_v2]

for nome, coluna in [
    ("Zero", "pred_variacao_zero"),
    ("Tendência 1M", "pred_variacao_tendencia")
]:

    pred = teste_v2[coluna]

    mae = mean_absolute_error(
        y_real,
        pred
    )

    rmse = np.sqrt(
        mean_squared_error(
            y_real,
            pred
        )
    )

    print("=" * 40)
    print(nome)
    print("=" * 40)
    print(f"MAE variação:  {mae:.4f} p.p.")
    print(f"RMSE variação: {rmse:.4f} p.p.")

========================================
Zero
========================================
MAE variação:  1.1120 p.p.
RMSE variação: 1.6596 p.p.
========================================
Tendência 1M
========================================
MAE variação:  1.4106 p.p.
RMSE variação: 2.2802 p.p.

In [117]:
teste_v2["preco_prev_zero"] = (
    teste_v2["preco"]
    * (
        1
        + teste_v2["pred_variacao_zero"] / 100
    )
)

In [118]:
teste_v2["preco_prev_tendencia"] = (
    teste_v2["preco"]
    * (
        1
        + teste_v2["pred_variacao_tendencia"] / 100
    )
)

In [119]:
teste_v2["preco_real_proximo_mes"] = (
    teste_v2["preco"]
    * (
        1
        + teste_v2[target_v2] / 100
    )
)

In [120]:
for nome, coluna in [
    ("Zero", "preco_prev_zero"),
    ("Tendência 1M", "preco_prev_tendencia")
]:

    real = teste_v2["preco_real_proximo_mes"]
    pred = teste_v2[coluna]

    mae = mean_absolute_error(real, pred)

    rmse = np.sqrt(
        mean_squared_error(real, pred)
    )

    mape = (
        np.abs(
            (real - pred) / real
        ).mean() * 100
    )

    print("=" * 40)
    print(f"BASELINE: {nome}")
    print("=" * 40)

    print(f"MAE:  R$ {mae:,.2f}")
    print(f"RMSE: R$ {rmse:,.2f}")
    print(f"MAPE: {mape:.4f}%")

========================================
BASELINE: Zero
========================================
MAE:  R$ 1,450.10
RMSE: R$ 6,690.64
MAPE: 1.1117%
========================================
BASELINE: Tendência 1M
========================================
MAE:  R$ 1,750.70
RMSE: R$ 8,472.15
MAPE: 1.4108%

In [121]:
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error
)

In [122]:
X_train = treino_v2[features_v2]
y_train = treino_v2[target_v2]

X_test = teste_v2[features_v2]
y_test = teste_v2[target_v2]

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)

X_train: (4612211, 7)
X_test : (585430, 7)

In [123]:
modelo_hgb = HistGradientBoostingRegressor(
    learning_rate=0.08,
    max_iter=150,
    max_leaf_nodes=31,
    min_samples_leaf=50,
    l2_regularization=1.0,
    random_state=42
)

modelo_hgb.fit(
    X_train,
    y_train
)

HistGradientBoostingRegressor(l2_regularization=1.0, learning_rate=0.08,
                              max_iter=150, min_samples_leaf=50,
                              random_state=42)

In [124]:
pred_variacao_hgb = modelo_hgb.predict(X_test)

In [125]:
mae_var_hgb = mean_absolute_error(
    y_test,
    pred_variacao_hgb
)

rmse_var_hgb = np.sqrt(
    mean_squared_error(
        y_test,
        pred_variacao_hgb
    )
)

print("=" * 45)
print("HIST GRADIENT BOOSTING — VARIAÇÃO")
print("=" * 45)

print(f"MAE:  {mae_var_hgb:.4f} p.p.")
print(f"RMSE: {rmse_var_hgb:.4f} p.p.")

=============================================
HIST GRADIENT BOOSTING — VARIAÇÃO
=============================================
MAE:  1.0782 p.p.
RMSE: 1.6588 p.p.

In [126]:
teste_v2["pred_variacao_hgb"] = pred_variacao_hgb

teste_v2["preco_prev_hgb"] = (
    teste_v2["preco"]
    * (
        1
        + teste_v2["pred_variacao_hgb"] / 100
    )
)

In [127]:
real = teste_v2["preco_real_proximo_mes"]
pred = teste_v2["preco_prev_hgb"]

mae_hgb = mean_absolute_error(
    real,
    pred
)

rmse_hgb = np.sqrt(
    mean_squared_error(
        real,
        pred
    )
)

mape_hgb = (
    np.abs(
        (real - pred) / real
    ).mean() * 100
)

print("=" * 45)
print("HIST GRADIENT BOOSTING — PREÇO")
print("=" * 45)

print(f"MAE:  R$ {mae_hgb:,.2f}")
print(f"RMSE: R$ {rmse_hgb:,.2f}")
print(f"MAPE: {mape_hgb:.4f}%")

=============================================
HIST GRADIENT BOOSTING — PREÇO
=============================================
MAE:  R$ 1,368.51
RMSE: R$ 6,396.98
MAPE: 1.0764%

In [128]:
placar = pd.DataFrame({
    "Modelo": [
        "Baseline Zero",
        "Tendência 1M",
        "HistGradientBoosting"
    ],

    "MAE_R$": [
        1450.10,
        1750.70,
        mae_hgb
    ],

    "RMSE_R$": [
        6690.64,
        8472.15,
        rmse_hgb
    ],

    "MAPE_%": [
        1.1117,
        1.4108,
        mape_hgb
    ]
})

placar = placar.sort_values("MAE_R$")

display(placar)

                 Modelo      MAE_R$     RMSE_R$    MAPE_%
2  HistGradientBoosting  1368.50762  6396.97822  1.076413
0         Baseline Zero  1450.10000  6690.64000  1.111700
1          Tendência 1M  1750.70000  8472.15000  1.410800

In [129]:
df_modelo_limpo["momentum_1_3"] = (
    df_modelo_limpo["variacao_mensal_pct"]
    - df_modelo_limpo["variacao_3m_pct"] / 3
)

df_modelo_limpo["momentum_3_6"] = (
    df_modelo_limpo["variacao_3m_pct"] / 3
    - df_modelo_limpo["variacao_6m_pct"] / 6
)

In [130]:
grupo = df_modelo_limpo.groupby(
    [
        "codigo_fipe",
        "ano_modelo",
        "sigla_combustivel"
    ],
    sort=False
)

df_modelo_limpo["volatilidade_6m"] = (
    grupo["variacao_mensal_pct"]
    .transform(
        lambda x: x.rolling(
            window=6,
            min_periods=3
        ).std()
    )
)

In [131]:
df_modelo_limpo["media_preco_6m"] = (
    grupo["preco"]
    .transform(
        lambda x: x.rolling(
            window=6,
            min_periods=3
        ).mean()
    )
)

df_modelo_limpo["dist_media_6m_pct"] = (
    (
        df_modelo_limpo["preco"]
        / df_modelo_limpo["media_preco_6m"]
    ) - 1
) * 100

In [132]:
features_v3 = [
    "idade_veiculo",
    "preco",
    "mes",

    "variacao_mensal_pct",
    "variacao_3m_pct",
    "variacao_6m_pct",
    "variacao_12m_pct",

    "momentum_1_3",
    "momentum_3_6",

    "volatilidade_6m",
    "dist_media_6m_pct"
]

In [133]:
display(
    df_modelo_limpo[
        [
            "momentum_1_3",
            "momentum_3_6",
            "volatilidade_6m",
            "dist_media_6m_pct"
        ]
    ].describe().round(3)
)

       momentum_1_3  momentum_3_6  volatilidade_6m  dist_media_6m_pct
count   5491318.000   5402513.000      5492277.000        5521887.000
mean         -0.007        -0.007            1.193             -0.369
std           1.239         0.655            0.952              2.545
min         -36.709       -19.573            0.000            -42.741
25%          -0.485        -0.298            0.511             -1.567
50%          -0.002        -0.002            1.022             -0.593
75%           0.449         0.283            1.662              0.640
max          74.706        20.226           45.298             83.122

In [134]:
for coluna in [
    "momentum_1_3",
    "momentum_3_6",
    "volatilidade_6m",
    "dist_media_6m_pct"
]:
    
    qtd = df_modelo_limpo[coluna].notna().sum()
    pct = qtd / len(df_modelo_limpo) * 100
    
    print(
        f"{coluna:22} "
        f"{qtd:>10,} "
        f"({pct:.2f}%)"
    )

momentum_1_3            5,491,318 (98.38%)
momentum_3_6            5,402,513 (96.79%)
volatilidade_6m         5,492,277 (98.40%)
dist_media_6m_pct       5,521,887 (98.93%)

In [135]:
features_v3 = [
    "idade_veiculo",
    "preco",
    "mes",

    "variacao_mensal_pct",
    "variacao_3m_pct",
    "variacao_6m_pct",
    "variacao_12m_pct",

    "momentum_1_3",
    "momentum_3_6",
    "volatilidade_6m",
    "dist_media_6m_pct"
]

target_v3 = "target_variacao_proximo_mes"

In [136]:
df_ml_v3 = df_modelo_limpo[
    [
        "codigo_fipe",
        "nome_marca",
        "nome_modelo",
        "sigla_combustivel",
        "ano_modelo",
        "data_referencia"
    ]
    + features_v3
    + [target_v3]
].dropna(
    subset=features_v3 + [target_v3]
).copy()

print(f"Registros ML V3: {len(df_ml_v3):,}")

Registros ML V3: 5,197,641

In [137]:
data_corte = pd.Timestamp("2025-01-01")

treino_v3 = df_ml_v3[
    df_ml_v3["data_referencia"] < data_corte
].copy()

teste_v3 = df_ml_v3[
    df_ml_v3["data_referencia"] >= data_corte
].copy()

print(f"Treino V3: {len(treino_v3):,}")
print(f"Teste V3:  {len(teste_v3):,}")

Treino V3: 4,612,211
Teste V3:  585,430

In [138]:
X_train_v3 = treino_v3[features_v3]
y_train_v3 = treino_v3[target_v3]

X_test_v3 = teste_v3[features_v3]
y_test_v3 = teste_v3[target_v3]

print("X_train:", X_train_v3.shape)
print("X_test :", X_test_v3.shape)

X_train: (4612211, 11)
X_test : (585430, 11)

In [139]:
from sklearn.ensemble import HistGradientBoostingRegressor

modelo_hgb_v3 = HistGradientBoostingRegressor(
    learning_rate=0.08,
    max_iter=150,
    max_leaf_nodes=31,
    min_samples_leaf=50,
    l2_regularization=1.0,
    random_state=42
)

modelo_hgb_v3.fit(
    X_train_v3,
    y_train_v3
)

HistGradientBoostingRegressor(l2_regularization=1.0, learning_rate=0.08,
                              max_iter=150, min_samples_leaf=50,
                              random_state=42)

In [140]:
pred_variacao_v3 = modelo_hgb_v3.predict(
    X_test_v3
)

In [141]:
teste_v3["pred_variacao_hgb_v3"] = pred_variacao_v3

teste_v3["preco_prev_hgb_v3"] = (
    teste_v3["preco"]
    * (
        1
        + teste_v3["pred_variacao_hgb_v3"] / 100
    )
)

teste_v3["preco_real_proximo_mes"] = (
    teste_v3["preco"]
    * (
        1
        + teste_v3[target_v3] / 100
    )
)

In [142]:
real_v3 = teste_v3["preco_real_proximo_mes"]
pred_v3 = teste_v3["preco_prev_hgb_v3"]

mae_v3 = mean_absolute_error(
    real_v3,
    pred_v3
)

rmse_v3 = np.sqrt(
    mean_squared_error(
        real_v3,
        pred_v3
    )
)

mape_v3 = (
    np.abs(
        (real_v3 - pred_v3) / real_v3
    ).mean() * 100
)

print("=" * 45)
print("HIST GRADIENT BOOSTING V3")
print("=" * 45)

print(f"MAE:  R$ {mae_v3:,.2f}")
print(f"RMSE: R$ {rmse_v3:,.2f}")
print(f"MAPE: {mape_v3:.4f}%")

=============================================
HIST GRADIENT BOOSTING V3
=============================================
MAE:  R$ 1,359.79
RMSE: R$ 6,376.31
MAPE: 1.0684%

In [143]:
placar_v3 = pd.DataFrame({
    "Modelo": [
        "Baseline Zero",
        "HGB V2",
        "HGB V3"
    ],

    "MAE_R$": [
        1450.10,
        1368.50762,
        mae_v3
    ],

    "RMSE_R$": [
        6690.64,
        6396.97822,
        rmse_v3
    ],

    "MAPE_%": [
        1.1117,
        1.076413,
        mape_v3
    ]
})

placar_v3 = placar_v3.sort_values(
    "MAE_R$"
)

display(placar_v3)

          Modelo       MAE_R$      RMSE_R$    MAPE_%
2         HGB V3  1359.789954  6376.314181  1.068420
1         HGB V2  1368.507620  6396.978220  1.076413
0  Baseline Zero  1450.100000  6690.640000  1.111700

In [144]:
features_numericas_v4 = [
    "idade_veiculo",
    "preco",
    "mes",
    "variacao_mensal_pct",
    "variacao_3m_pct",
    "variacao_6m_pct",
    "variacao_12m_pct",
    "momentum_1_3",
    "momentum_3_6",
    "volatilidade_6m",
    "dist_media_6m_pct"
]

features_categoricas_v4 = [
    "nome_marca",
    "sigla_combustivel"
]

features_v4 = (
    features_numericas_v4
    + features_categoricas_v4
)

In [145]:
df_ml_v4 = df_modelo_limpo[
    [
        "codigo_fipe",
        "nome_modelo",
        "ano_modelo",
        "data_referencia"
    ]
    + features_v4
    + [target_v3]
].dropna(
    subset=features_v4 + [target_v3]
).copy()

print(f"Registros ML V4: {len(df_ml_v4):,}")

Registros ML V4: 5,197,641

In [146]:
for coluna in features_categoricas_v4:
    df_ml_v4[coluna] = (
        df_ml_v4[coluna]
        .astype("category")
    )

In [147]:
print(df_ml_v4[features_categoricas_v4].dtypes)

print(
    "\nMarcas:",
    df_ml_v4["nome_marca"].nunique()
)

print(
    "Combustíveis:",
    df_ml_v4["sigla_combustivel"].nunique()
)

nome_marca           category
sigla_combustivel    category
dtype: object

Marcas: 104
Combustíveis: 7

In [148]:
treino_v4 = df_ml_v4[
    df_ml_v4["data_referencia"] < data_corte
].copy()

teste_v4 = df_ml_v4[
    df_ml_v4["data_referencia"] >= data_corte
].copy()

print(f"Treino V4: {len(treino_v4):,}")
print(f"Teste V4:  {len(teste_v4):,}")

Treino V4: 4,612,211
Teste V4:  585,430

In [149]:
for coluna in features_categoricas_v4:

    categorias = treino_v4[coluna].cat.categories

    treino_v4[coluna] = (
        treino_v4[coluna]
        .cat.set_categories(categorias)
    )

    teste_v4[coluna] = (
        teste_v4[coluna]
        .cat.set_categories(categorias)
    )

In [150]:
X_train_v4 = treino_v4[features_v4]
y_train_v4 = treino_v4[target_v3]

X_test_v4 = teste_v4[features_v4]
y_test_v4 = teste_v4[target_v3]

In [151]:
modelo_hgb_v4 = HistGradientBoostingRegressor(
    learning_rate=0.08,
    max_iter=150,
    max_leaf_nodes=31,
    min_samples_leaf=50,
    l2_regularization=1.0,
    categorical_features="from_dtype",
    random_state=42
)

modelo_hgb_v4.fit(
    X_train_v4,
    y_train_v4
)

HistGradientBoostingRegressor(l2_regularization=1.0, learning_rate=0.08,
                              max_iter=150, min_samples_leaf=50,
                              random_state=42)

In [152]:
pred_variacao_v4 = modelo_hgb_v4.predict(
    X_test_v4
)

teste_v4["pred_variacao_hgb_v4"] = (
    pred_variacao_v4
)

teste_v4["preco_prev_hgb_v4"] = (
    teste_v4["preco"]
    * (
        1
        + teste_v4["pred_variacao_hgb_v4"] / 100
    )
)

teste_v4["preco_real_proximo_mes"] = (
    teste_v4["preco"]
    * (
        1
        + teste_v4[target_v3] / 100
    )
)

In [153]:
real_v4 = teste_v4["preco_real_proximo_mes"]
pred_v4 = teste_v4["preco_prev_hgb_v4"]

mae_v4 = mean_absolute_error(real_v4, pred_v4)

rmse_v4 = np.sqrt(
    mean_squared_error(real_v4, pred_v4)
)

mape_v4 = (
    np.abs(
        (real_v4 - pred_v4) / real_v4
    ).mean() * 100
)

print("=" * 45)
print("HIST GRADIENT BOOSTING V4")
print("=" * 45)

print(f"MAE:  R$ {mae_v4:,.2f}")
print(f"RMSE: R$ {rmse_v4:,.2f}")
print(f"MAPE: {mape_v4:.4f}%")

=============================================
HIST GRADIENT BOOSTING V4
=============================================
MAE:  R$ 1,358.42
RMSE: R$ 6,381.20
MAPE: 1.0689%

In [154]:
placar_v4 = pd.DataFrame({
    "Modelo": [
        "Baseline Zero",
        "HGB V2",
        "HGB V3",
        "HGB V4"
    ],
    "MAE_R$": [
        1450.10,
        1368.507620,
        1359.789954,
        mae_v4
    ],
    "RMSE_R$": [
        6690.64,
        6396.978220,
        6376.314181,
        rmse_v4
    ],
    "MAPE_%": [
        1.1117,
        1.076413,
        1.068420,
        mape_v4
    ]
})

display(
    placar_v4.sort_values("MAE_R$")
)

          Modelo       MAE_R$      RMSE_R$    MAPE_%
3         HGB V4  1358.421567  6381.197030  1.068905
2         HGB V3  1359.789954  6376.314181  1.068420
1         HGB V2  1368.507620  6396.978220  1.076413
0  Baseline Zero  1450.100000  6690.640000  1.111700

In [155]:
janelas = [
    ("2024", "2024-01-01", "2025-01-01"),
    ("2025", "2025-01-01", "2026-01-01"),
    ("2026", "2026-01-01", "2027-01-01")
]

resultados_temporais = []

In [156]:
for nome, inicio, fim in janelas:

    inicio = pd.Timestamp(inicio)
    fim = pd.Timestamp(fim)

    treino = df_ml_v3[
        df_ml_v3["data_referencia"] < inicio
    ].copy()

    teste = df_ml_v3[
        (df_ml_v3["data_referencia"] >= inicio) &
        (df_ml_v3["data_referencia"] < fim)
    ].copy()

    X_train = treino[features_v3]
    y_train = treino[target_v3]

    X_test = teste[features_v3]
    y_test = teste[target_v3]

    modelo = HistGradientBoostingRegressor(
        learning_rate=0.08,
        max_iter=150,
        max_leaf_nodes=31,
        min_samples_leaf=50,
        l2_regularization=1.0,
        random_state=42
    )

    modelo.fit(X_train, y_train)

    pred_var = modelo.predict(X_test)

    preco_real = (
        teste["preco"]
        * (1 + y_test / 100)
    )

    preco_prev = (
        teste["preco"]
        * (1 + pred_var / 100)
    )

    mae = mean_absolute_error(
        preco_real,
        preco_prev
    )

    rmse = np.sqrt(
        mean_squared_error(
            preco_real,
            preco_prev
        )
    )

    mape = (
        np.abs(
            (preco_real - preco_prev)
            / preco_real
        ).mean() * 100
    )

    # baseline: preço atual
    mae_baseline = mean_absolute_error(
        preco_real,
        teste["preco"]
    )

    resultados_temporais.append({
        "Periodo": nome,
        "Treino": len(treino),
        "Teste": len(teste),
        "MAE_Modelo": mae,
        "MAE_Baseline": mae_baseline,
        "RMSE_Modelo": rmse,
        "MAPE_Modelo": mape
    })

    print(f"{nome} concluído")

2024 concluído
2025 concluído
2026 concluído

In [157]:
validacao_temporal = pd.DataFrame(
    resultados_temporais
)

validacao_temporal["Ganho_MAE_%"] = (
    (
        validacao_temporal["MAE_Baseline"]
        - validacao_temporal["MAE_Modelo"]
    )
    / validacao_temporal["MAE_Baseline"]
    * 100
)

display(
    validacao_temporal.round(3)
)

,Periodo,Treino,Teste,MAE_Modelo,MAE_Baseline,RMSE_Modelo,MAPE_Modelo,Ganho_MAE_%
0,2024,4290221,321990,1472.972,1572.262,5923.028,1.233,6.315
1,2025,4612211,331160,1384.063,1452.473,6834.452,1.096,4.710
2,2026,4943371,254270,1324.859,1447.013,5704.421,1.032,8.442

In [158]:
teste["preco_real"] = preco_real
teste["preco_previsto"] = preco_prev

teste["erro_abs"] = (
    teste["preco_real"]
    - teste["preco_previsto"]
).abs()

teste["erro_pct"] = (
    teste["erro_abs"]
    / teste["preco_real"]
) * 100

In [159]:
teste["faixa_preco"] = pd.cut(
    teste["preco"],
    bins=[
        0,
        30000,
        60000,
        100000,
        200000,
        500000,
        float("inf")
    ],
    labels=[
        "Até 30k",
        "30k–60k",
        "60k–100k",
        "100k–200k",
        "200k–500k",
        "500k+"
    ]
)

erro_faixa = (
    teste
    .groupby(
        "faixa_preco",
        observed=True
    )
    .agg(
        Veiculos=("erro_abs", "size"),
        MAE=("erro_abs", "mean"),
        MAPE=("erro_pct", "mean")
    )
    .round(2)
)

display(erro_faixa)

             Veiculos       MAE  MAPE
faixa_preco
Até 30k         82788    166.88  0.90
30k–60k         62038    508.21  1.17
60k–100k        41585    791.43  1.03
100k–200k       35398   1499.62  1.06
200k–500k       22197   3272.68  1.10
500k+           10264  12947.11  1.00

In [160]:
piores_2026 = (
    teste
    .sort_values(
        "erro_pct",
        ascending=False
    )
    [
        [
            "codigo_fipe",
            "nome_marca",
            "nome_modelo",
            "ano_modelo",
            "data_referencia",
            "preco",
            "preco_real",
            "preco_previsto",
            "erro_abs",
            "erro_pct"
        ]
    ]
    .head(20)
)

display(piores_2026)

,codigo_fipe,nome_marca,nome_modelo,ano_modelo,data_referencia,preco,preco_real,preco_previsto,erro_abs,erro_pct
4256957,017084-4,Jeep,Grand Cherokee 80 Anos 3.0 TB Dies.Aut.,2021.0,2026-09-01,398589.0,310201.0,3.974853e+05,87284.288420,28.137978
9078836,005258-2,VW - VolksWagen,Polo GTI 1.8 Mi 150cv 20V Turbo 3p,2007.0,2026-08-01,145108.0,117541.0,1.464210e+05,28879.950148,24.570108
1999173,001279-3,Fiat,Siena HLX Dualogic 1.8 mpi Flex 8V 4p,2010.0,2026-01-01,30201.0,39854.0,3.020862e+04,9645.383887,24.201796
6753970,025086-4,Renault,Clio Expression 1.0/1.0 Hi-Power 16V 3p,2005.0,2026-09-01,16253.0,13521.0,1.627349e+04,2752.494680,20.357183
5830216,021200-8,Mercedes-Benz,S-65 AMG 6.0 V12 612cv Aut,2010.0,2026-09-01,371515.0,315451.0,3.708330e+05,55382.036992,17.556463
5830421,021200-8,Mercedes-Benz,S-65 AMG 6.0 V12 612cv Aut,2011.0,2026-09-01,388220.0,330201.0,3.874453e+05,57244.267087,17.336188
5831013,021359-4,Mercedes-Benz,S-65 L AMG 6.0 V12 630cv Aut.,2018.0,2026-09-01,1147689.0,985632.0,1.145738e+06,160105.913821,16.243985
7736776,028014-3,Suzuki,Grand Vitara 2.5 V6 5p Mec.,2002.0,2026-08-01,26073.0,31021.0,2.604448e+04,4976.520242,16.042424
5822624,021083-8,Mercedes-Benz,S-600 L/ L Classic/ Wagon Classic 6.0,2011.0,2026-09-01,345772.0,297541.0,3.451503e+05,47609.300047,16.000921
7736159,028014-3,Suzuki,Grand Vitara 2.5 V6 5p Mec.,2000.0,2026-08-01,22382.0,26521.0,2.234577e+04,4175.225819,15.743093
7736469,028014-3,Suzuki,Grand Vitara 2.5 V6 5p Mec.,2001.0,2026-08-01,25437.0,30102.0,2.542971e+04,4672.294311,15.521541
5821741,021083-8,Mercedes-Benz,S-600 L/ L Classic/ Wagon Classic 6.0,2007.0,2026-09-01,230732.0,199562.0,2.303394e+05,30777.360669,15.422456
5926165,021430-2,Mercedes-Benz,Sprinter 314 Furgão Longo T.B. 2.2 Dies.,2020.0,2026-09-01,183182.0,159985.0,1.836447e+05,23659.726335,14.788715
5862418,021303-9,Mercedes-Benz,SLS-63 AMG 6.2 8V Black Series Aut.,2014.0,2026-09-01,1493311.0,1765521.0,1.505566e+06,259954.778543,14.723970
2270183,003008-2,Ford,Escort S.W. GLX 1.8i 16V,1997.0,2026-09-01,7322.0,8562.0,7.310777e+03,1251.223149,14.613678
7742317,028039-9,Suzuki,Grand Vitara XL_7 2.7 24V 173cv 4p Mec.,2002.0,2026-08-01,27494.0,32021.0,2.744419e+04,4576.813427,14.293162
7735849,028014-3,Suzuki,Grand Vitara 2.5 V6 5p Mec.,1999.0,2026-08-01,21836.0,25412.0,2.180066e+04,3611.342104,14.211168
5829771,021200-8,Mercedes-Benz,S-65 AMG 6.0 V12 612cv Aut,2008.0,2026-09-01,338086.0,295521.0,3.374971e+05,41976.093703,14.204098
6753695,025086-4,Renault,Clio Expression 1.0/1.0 Hi-Power 16V 3p,2004.0,2026-09-01,13572.0,12021.0,1.372107e+04,1700.067651,14.142481
8879161,005099-7,VW - VolksWagen,Golf GTI VR6/ Golf 2.8 VR6,2003.0,2026-09-01,153943.0,135521.0,1.546330e+05,19111.995667,14.102608

In [162]:
from sklearn.ensemble import HistGradientBoostingRegressor

X_final = df_ml_v3[features_v3]
y_final = df_ml_v3[target_v3]

modelo_final = HistGradientBoostingRegressor(
    learning_rate=0.08,
    max_iter=150,
    max_leaf_nodes=31,
    min_samples_leaf=50,
    l2_regularization=1.0,
    random_state=42
)

modelo_final.fit(
    X_final,
    y_final
)

print("Modelo final treinado.")
print(f"Registros utilizados: {len(X_final):,}")
print(f"Features: {len(features_v3)}")

Modelo final treinado.
Registros utilizados: 5,197,641
Features: 11

In [163]:
import joblib
from pathlib import Path

PASTA_MODELO = Path("modelo")
PASTA_MODELO.mkdir(exist_ok=True)

joblib.dump(
    modelo_final,
    PASTA_MODELO / "autoinsight_hgb_v1.joblib"
)

print("Modelo salvo!")

Modelo salvo!

In [164]:
list(PASTA_MODELO.iterdir())

[WindowsPath('modelo/autoinsight_hgb_v1.joblib')]

In [165]:
import json

metadata = {
    "nome": "AutoInsight ML",
    "versao": "1.0",
    "algoritmo": "HistGradientBoostingRegressor",
    "target": target_v3,
    "features": features_v3,
    "data_ultimo_registro": str(
        df_ml_v3["data_referencia"].max().date()
    ),
    "metricas_referencia": {
        "mae": 1359.79,
        "rmse": 6376.31,
        "mape": 1.0684
    }
}

with open(
    PASTA_MODELO / "metadata.json",
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        metadata,
        f,
        indent=4,
        ensure_ascii=False
    )

In [166]:
import json

metadata = {
    "nome": "AutoInsight ML",
    "versao": "1.0",
    "algoritmo": "HistGradientBoostingRegressor",
    "target": target_v3,
    "features": features_v3,
    "data_ultimo_registro": str(
        df_ml_v3["data_referencia"].max().date()
    ),
    "metricas_referencia": {
        "mae": 1359.79,
        "rmse": 6376.31,
        "mape": 1.0684
    }
}

with open(
    PASTA_MODELO / "metadata.json",
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        metadata,
        f,
        indent=4,
        ensure_ascii=False
    )

print("Metadata salvo!")

for arquivo in PASTA_MODELO.iterdir():
    print(arquivo)

Metadata salvo!
modelo\autoinsight_hgb_v1.joblib
modelo\metadata.json

In [167]:
from pathlib import Path

print(Path.cwd())

C:\Users\Clebe\Downloads\AutoInsight AI

In [168]:
from pathlib import Path

Path("api").mkdir(exist_ok=True)

Path("api/__init__.py").touch()

print("Estrutura criada.")

Estrutura criada.

In [169]:
import sys
import sklearn
import joblib
import numpy
import pandas

print("Python:", sys.version)
print("scikit-learn:", sklearn.__version__)
print("joblib:", joblib.__version__)
print("numpy:", numpy.__version__)
print("pandas:", pandas.__version__)

Python: 3.14.7 (tags/v3.14.7:823f032, Aug  5 2026, 10:51:32) [MSC v.1944 64 bit (AMD64)]
scikit-learn: 1.8.0
joblib: 1.5.3
numpy: 2.4.2
pandas: 2.3.3

In [170]:
colunas_api = [
    "codigo_fipe",
    "nome_marca",
    "nome_modelo",
    "nome_combustivel",
    "sigla_combustivel",
    "ano_modelo",
    "data_referencia",
    "preco"
]

df_api = (
    df_modelo_limpo[colunas_api]
    .sort_values(
        ["codigo_fipe", "ano_modelo", "data_referencia"]
    )
    .copy()
)

print(f"Registros: {len(df_api):,}")
print(f"Veículos: {df_api[['codigo_fipe', 'ano_modelo']].drop_duplicates().shape[0]:,}")

display(df_api.tail())

Registros: 5,581,538
Veículos: 29,521

,codigo_fipe,nome_marca,nome_modelo,nome_combustivel,sigla_combustivel,ano_modelo,data_referencia,preco
896853,308005-6,Caoa Changan,CS55 INFINITY 1.5 16V TGDi,Flex,f,2027.0,2026-10-01,146166.0
896857,308006-4,Caoa Changan,CS55 ULTRA 1.5 16V TGDi,Híbrido,h,2027.0,2026-10-01,178201.0
113390,309001-9,ARROW,2 Urban Cargo 85 5m³,Elétrico,l,2026.0,2026-10-01,203328.0
113392,309002-7,ARROW,2 Urban Cargo 85 7m³,Elétrico,l,2026.0,2026-10-01,209227.0
113394,309003-5,ARROW,2 Urban Chassi 85,Elétrico,l,2026.0,2026-10-01,190366.0

In [171]:
df_api_24m = (
    df_api
    .groupby(
        ["codigo_fipe", "ano_modelo"],
        group_keys=False
    )
    .tail(24)
    .reset_index(drop=True)
)

print(f"Base completa: {len(df_api):,}")
print(f"Base API:      {len(df_api_24m):,}")

Base completa: 5,581,538
Base API:      679,756

In [172]:
from pathlib import Path

PASTA_DATA = Path("data")
PASTA_DATA.mkdir(exist_ok=True)

df_api_24m.to_parquet(
    PASTA_DATA / "fipe_api.parquet",
    index=False
)

print("Base da API salva!")

Base da API salva!

In [173]:
arquivo = PASTA_DATA / "fipe_api.parquet"

print(
    "Tamanho:",
    round(arquivo.stat().st_size / 1024**2, 2),
    "MB"
)

Tamanho: 3.16 MB

In [174]:
argos_api = (
    df_api_24m[
        df_api_24m["nome_modelo"]
        .str.contains("ARGO", case=False, na=False)
    ]
    [
        [
            "codigo_fipe",
            "nome_marca",
            "nome_modelo",
            "ano_modelo"
        ]
    ]
    .drop_duplicates()
    .sort_values(
        ["nome_modelo", "ano_modelo"]
    )
)

display(argos_api)

,codigo_fipe,nome_marca,nome_modelo,ano_modelo
679753,309001-9,ARROW,2 Urban Cargo 85 5m³,2026.0
679754,309002-7,ARROW,2 Urban Cargo 85 7m³,2026.0
50131,001509-1,Fiat,ARGO 1.0 6V Flex,2018.0
50155,001509-1,Fiat,ARGO 1.0 6V Flex,2019.0
50179,001509-1,Fiat,ARGO 1.0 6V Flex,2020.0
...,...,...,...,...
674985,091004-0,HITECH ELECTRIC,"e.co Cargo 7,5kW (Elétrico)",2021.0
675009,091004-0,HITECH ELECTRIC,"e.co Cargo 7,5kW (Elétrico)",2022.0
675417,091011-2,HITECH ELECTRIC,"e.coCargo 31,4 kW (Elétrico)",2024.0
332803,011218-6,Citroën,Ë-Jumpy Cargo 136cv (Elétrico),2022.0
332827,011218-6,Citroën,Ë-Jumpy Cargo 136cv (Elétrico),2023.0

In [175]:
display(
    argos_api[
        argos_api["ano_modelo"] == 2024
    ]
)

,codigo_fipe,nome_marca,nome_modelo,ano_modelo
50275,001509-1,Fiat,ARGO 1.0 6V Flex,2024.0
48752,001494-0,Fiat,ARGO DRIVE 1.0 6V Flex,2024.0
54337,001561-0,Fiat,ARGO DRIVE 1.3 8V Flex Aut.,2024.0
51085,001519-9,Fiat,ARGO TREKKING 1.3 8V Flex,2024.0
54427,001562-8,Fiat,ARGO TREKKING 1.3 8V Flex Aut.,2024.0
511126,024262-4,Peugeot,Boxer Cargo 2.2 Turbo Diesel,2024.0
54517,001563-6,Fiat,Ducato Cargo 2.2 Diesel (E6),2024.0
54603,001564-4,Fiat,Ducato MaxiCargo 2.2 Diesel (E6),2024.0
510923,024260-8,Peugeot,Expert Cargo 1.5 Turbo Diesel,2024.0
333005,011220-8,Citroën,Jumper Cargo 2.2 Turbo Diesel,2024.0
332659,011216-0,Citroën,Jumpy Cargo 1.5 Turbo Diesel,2024.0
53552,001550-4,Fiat,Scudo Cargo 1.5 16V Turbo Diesel,2024.0
675393,091010-4,HITECH ELECTRIC,e.co Cargo 15.7kWh (Elétrico),2024.0
675417,091011-2,HITECH ELECTRIC,"e.coCargo 31,4 kW (Elétrico)",2024.0

In [176]:
comparacao_argo = (
    df_modelo_limpo[
        (df_modelo_limpo["codigo_fipe"] == "001494-0")
        &
        (df_modelo_limpo["ano_modelo"] == 2024)
        &
        (
            df_modelo_limpo["data_referencia"]
            == pd.Timestamp("2026-10-01")
        )
    ]
)

colunas_comparacao = [
    "codigo_fipe",
    "nome_modelo",
    "ano_modelo",
    "data_referencia",
    "idade_veiculo",
    "preco",
    "mes",
    "variacao_mensal_pct",
    "variacao_3m_pct",
    "variacao_6m_pct",
    "variacao_12m_pct",
    "momentum_1_3",
    "momentum_3_6",
    "volatilidade_6m",
    "dist_media_6m_pct"
]

display(
    comparacao_argo[
        colunas_comparacao
    ].T
)

                                    1661442
codigo_fipe                        001494-0
nome_modelo          ARGO DRIVE 1.0 6V Flex
ano_modelo                           2024.0
data_referencia         2026-10-01 00:00:00
idade_veiculo                           2.0
preco                               67386.0
mes                                      10
variacao_mensal_pct               -0.601823
variacao_3m_pct                   -1.614787
variacao_6m_pct                   -1.769679
variacao_12m_pct                  -3.599325
momentum_1_3                      -0.063561
momentum_3_6                      -0.243316
volatilidade_6m                    0.742129
dist_media_6m_pct                 -1.354101

In [177]:
display(
    df_modelo_limpo[
        (df_modelo_limpo["codigo_fipe"] == "001494-0")
        & (df_modelo_limpo["ano_modelo"] == 2024)
    ][
        [
            "data_referencia",
            "preco",
            "variacao_mensal_pct",
            "variacao_3m_pct",
            "variacao_6m_pct",
            "momentum_1_3",
            "momentum_3_6"
        ]
    ]
    .sort_values("data_referencia")
    .tail(10)
)

,data_referencia,preco,variacao_mensal_pct,variacao_3m_pct,variacao_6m_pct,momentum_1_3,momentum_3_6
1661451,2026-01-01,69420.0,0.246935,-0.689537,-2.274903,0.476781,0.149305
1661450,2026-02-01,69215.0,-0.295304,-1.105888,-1.575587,0.073325,-0.106032
1661449,2026-03-01,68804.0,-0.593802,-0.642609,-1.866986,-0.379599,0.096962
1661448,2026-04-01,68600.0,-0.296494,-1.181216,-1.862608,0.097244,-0.083304
1661447,2026-05-01,68498.0,-0.148688,-1.035903,-2.130335,0.196613,0.009755
1661446,2026-06-01,69044.0,0.797104,0.348817,-0.296033,0.680831,0.165611
1661445,2026-07-01,68492.0,-0.799490,-0.157434,-1.336791,-0.747012,0.170320
1661444,2026-08-01,68652.0,0.233604,0.224824,-0.813407,0.158663,0.210509
1661443,2026-09-01,67794.0,-1.249782,-1.810440,-1.467938,-0.646302,-0.358824
1661442,2026-10-01,67386.0,-0.601823,-1.614787,-1.769679,-0.063561,-0.243316